// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_labels.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentsByLabelValue = `-- name: CountAgentsByLabelValue :many
SELECT value, COUNT(*)::bigint AS count
FROM agent_labels
WHERE key = $1
GROUP BY value
ORDER BY count DESC, value ASC
`

type CountAgentsByLabelValueRow struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}

// Fleet breakdown by a single label key.
func (q *Queries) CountAgentsByLabelValue(ctx context.Context, key string) ([]CountAgentsByLabelValueRow, error) {
	rows, err := q.db.Query(ctx, countAgentsByLabelValue, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAgentsByLabelValueRow{}
	for rows.Next() {
		var i CountAgentsByLabelValueRow
		if err := rows.Scan(&i.Value, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserLabel = `-- name: DeleteUserLabel :execrows
DELETE FROM agent_labels
WHERE agent_id = $1
	AND key = $2
	AND source = 'user'
`

type DeleteUserLabelParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
}

// Returns rows affected. Zero means either not found or exists but
// is auto-sourced; caller can disambiguate with GetAgentLabel.
func (q *Queries) DeleteUserLabel(ctx context.Context, arg DeleteUserLabelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserLabel, arg.AgentID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentLabel = `-- name: GetAgentLabel :one
SELECT key, value, source, updated_at
FROM agent_labels
WHERE agent_id = $1 AND key = $2
`

type GetAgentLabelParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
}

type GetAgentLabelRow struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	Source    string             `json:"source"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Single label lookup; used by the API to disambiguate 404 vs 403 (auto label
// the caller tried to modify) before calling a write query.
func (q *Queries) GetAgentLabel(ctx context.Context, arg GetAgentLabelParams) (GetAgentLabelRow, error) {
	row := q.db.QueryRow(ctx, getAgentLabel, arg.AgentID, arg.Key)
	var i GetAgentLabelRow
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentLabels = `-- name: ListAgentLabels :many

SELECT key, value, source, updated_at
FROM agent_labels
WHERE agent_id = $1
ORDER BY source DESC, key ASC
`

type ListAgentLabelsRow struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	Source    string             `json:"source"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// agent_labels
//
// Conventions:
//   - User writes go through UpsertUserLabel / DeleteUserLabel.
//   - Auto-label sync goes through ReplaceAutoLabels (one call per
//     agent register / heartbeat; idempotent).
//   - The ON CONFLICT WHERE clauses ensure auto and user labels can
//     never clobber each other regardless of caller mistake.
//
// All labels for one agent. Auto labels listed first so the UI can group them.
func (q *Queries) ListAgentLabels(ctx context.Context, agentID pgtype.UUID) ([]ListAgentLabelsRow, error) {
	rows, err := q.db.Query(ctx, listAgentLabels, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentLabelsRow{}
	for rows.Next() {
		var i ListAgentLabelsRow
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentLabelsForAgents = `-- name: ListAgentLabelsForAgents :many
SELECT agent_id, key, value, source
FROM agent_labels
WHERE agent_id = ANY($1::uuid[])
ORDER BY agent_id, source DESC, key ASC
`

type ListAgentLabelsForAgentsRow struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
	Value   string      `json:"value"`
	Source  string      `json:"source"`
}

// Batch label fetch for fleet/overview pages. Returns one row per (agent_id,
// key); caller groups by agent_id.
func (q *Queries) ListAgentLabelsForAgents(ctx context.Context, agentIds []pgtype.UUID) ([]ListAgentLabelsForAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgentLabelsForAgents, agentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentLabelsForAgentsRow{}
	for rows.Next() {
		var i ListAgentLabelsForAgentsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.Key,
			&i.Value,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByLabel = `-- name: ListAgentsByLabel :many
SELECT agent_id
FROM agent_labels
WHERE key = $1 and value = $2
`

type ListAgentsByLabelParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// Agents matching a single key=value pair.
func (q *Queries) ListAgentsByLabel(ctx context.Context, arg ListAgentsByLabelParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentsByLabel, arg.Key, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var agent_id pgtype.UUID
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByLabels = `-- name: ListAgentsByLabels :many
SELECT al.agent_id
FROM agent_labels AS al
JOIN (
    SELECT keys.k_val, vals.v_val
    FROM unnest($1::text[]) WITH ORDINALITY AS keys(k_val, idx)
    JOIN unnest($2::text[]) WITH ORDINALITY AS vals(v_val, idx)
        USING (idx)
) AS f ON al.key = f.k_val AND al.value = f.v_val
GROUP BY al.agent_id
HAVING COUNT(*) = COALESCE(array_length($1::text[], 1), 0)
`

type ListAgentsByLabelsParams struct {
	Keys   []string `json:"keys"`
	Values []string `json:"values"`
}

// Agents matching ALL of the given (key, value) pairs.
//
// @keys and @values must be parallel arrays of equal length.
func (q *Queries) ListAgentsByLabels(ctx context.Context, arg ListAgentsByLabelsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentsByLabels, arg.Keys, arg.Values)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var agent_id pgtype.UUID
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAgentLabels = `-- name: ListAllAgentLabels :many
SELECT agent_id, key, value, source
FROM agent_labels
ORDER BY agent_id, source DESC, key ASC
`

type ListAllAgentLabelsRow struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
	Value   string      `json:"value"`
	Source  string      `json:"source"`
}

// Every agent's labels in one query (for the overview/fleet pages). Caller
// groups by agent_id. Auto labels first for UI grouping.
func (q *Queries) ListAllAgentLabels(ctx context.Context) ([]ListAllAgentLabelsRow, error) {
	rows, err := q.db.Query(ctx, listAllAgentLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAgentLabelsRow{}
	for rows.Next() {
		var i ListAllAgentLabelsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.Key,
			&i.Value,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelKeys = `-- name: ListLabelKeys :many
SELECT DISTINCT key, source
FROM agent_labels
ORDER BY source DESC, key ASC
`

type ListLabelKeysRow struct {
	Key    string `json:"key"`
	Source string `json:"source"`
}

// Distinct keys across the fleet, for the rule-editor key picker.
// Includes source so the UI can flag auto keys as read-only.
func (q *Queries) ListLabelKeys(ctx context.Context) ([]ListLabelKeysRow, error) {
	rows, err := q.db.Query(ctx, listLabelKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelKeysRow{}
	for rows.Next() {
		var i ListLabelKeysRow
		if err := rows.Scan(&i.Key, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelValuesForKey = `-- name: ListLabelValuesForKey :many
SELECT DISTINCT value
FROM agent_labels
WHERE key = $1
ORDER BY value ASC
`

// Distinct values for a key, for the rule-editor value autocomplete.
func (q *Queries) ListLabelValuesForKey(ctx context.Context, key string) ([]string, error) {
	rows, err := q.db.Query(ctx, listLabelValuesForKey, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceAutoLabels = `-- name: ReplaceAutoLabels :exec
WITH new_labels AS (
    SELECT keys.k_val AS k, vals.v_val AS v
    FROM unnest($2::text[]) WITH ORDINALITY AS keys(k_val, idx)
    JOIN unnest($3::text[]) WITH ORDINALITY AS vals(v_val, idx)
        USING (idx)
),
deleted AS (
    DELETE FROM agent_labels al
    WHERE al.agent_id = $1
      AND al.source = 'auto'
      AND NOT EXISTS (
          SELECT 1 FROM new_labels nl WHERE nl.k = al.key
      )
    RETURNING 1
)
INSERT INTO agent_labels (agent_id, key, value, source, updated_at)
SELECT $1, k, v, 'auto', NOW() FROM new_labels
ON CONFLICT (agent_id, key)
DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = NOW()
WHERE agent_labels.source = 'auto'
  AND agent_labels.value IS DISTINCT FROM EXCLUDED.value
`

type ReplaceAutoLabelsParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Keys    []string    `json:"keys"`
	Values  []string    `json:"values"`
}

// Idempotent sync of all auto labels for an agent in a single statement.
// Called on agent registration and on detected version drift.
//
// Behavior:
//  1. Auto labels that aren't in the new set are removed.
//  2. New auto labels are inserted.
//  3. Existing auto labels are updated if value changed.
//  4. User labels are never touched.
//
// @keys and @values are parallel arrays. Empty arrays clear all auto labels
// for the agent.
func (q *Queries) ReplaceAutoLabels(ctx context.Context, arg ReplaceAutoLabelsParams) error {
	_, err := q.db.Exec(ctx, replaceAutoLabels, arg.AgentID, arg.Keys, arg.Values)
	return err
}

const upsertAutoLabel = `-- name: UpsertAutoLabel :exec
INSERT INTO agent_labels (agent_id, key, value, source, updated_at)
VALUES ($1, $2, $3, 'auto', NOW())
ON CONFLICT (agent_id, key)
DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
WHERE agent_labels.source = 'auto'
    AND agent_labels.value IS DISTINCT FROM EXCLUDED.value
`

type UpsertAutoLabelParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
	Value   string      `json:"value"`
}

// Single-label auto upsert for hot paths (metrics-handler version drift)
// that update one label without re-syncing the whole set. Same guards as
// ReplaceAutoLabels: never clobbers user labels, skips writes when value
// is unchanged.
func (q *Queries) UpsertAutoLabel(ctx context.Context, arg UpsertAutoLabelParams) error {
	_, err := q.db.Exec(ctx, upsertAutoLabel, arg.AgentID, arg.Key, arg.Value)
	return err
}

const upsertUserLabel = `-- name: UpsertUserLabel :one
INSERT INTO agent_labels (agent_id, key, value, source, updated_at)
VALUES ($1, $2, $3, 'user', NOW())
ON CONFLICT (agent_id, key)
DO UPDATE SET
	value = EXCLUDED.value,
	updated_at = NOW()
WHERE agent_labels.source = 'user'
RETURNING agent_id, key, value, source, updated_at
`

type UpsertUserLabelParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
	Value   string      `json:"value"`
}

// Admin-only write. The Go layer must reject reserved keys before
// calling this - the reserved set lives in code, not the DB.
//
// Returns NULL if no row was inserted/updated (caller should check).
func (q *Queries) UpsertUserLabel(ctx context.Context, arg UpsertUserLabelParams) (AgentLabel, error) {
	row := q.db.QueryRow(ctx, upsertUserLabel, arg.AgentID, arg.Key, arg.Value)
	var i AgentLabel
	err := row.Scan(
		&i.AgentID,
		&i.Key,
		&i.Value,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}
