// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_config.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgentConfig = `-- name: DeleteAgentConfig :exec
DELETE FROM agent_config
WHERE agent_id = $1 AND config_key = $2
`

type DeleteAgentConfigParams struct {
	AgentID   pgtype.UUID `json:"agent_id"`
	ConfigKey string      `json:"config_key"`
}

func (q *Queries) DeleteAgentConfig(ctx context.Context, arg DeleteAgentConfigParams) error {
	_, err := q.db.Exec(ctx, deleteAgentConfig, arg.AgentID, arg.ConfigKey)
	return err
}

const deleteAllAgentConfig = `-- name: DeleteAllAgentConfig :exec
DELETE FROM agent_config
WHERE agent_id = $1
`

func (q *Queries) DeleteAllAgentConfig(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllAgentConfig, agentID)
	return err
}

const getAgentConfig = `-- name: GetAgentConfig :many
SELECT agent_id, config_key, config_value, updated_at
FROM agent_config
WHERE agent_id = $1
ORDER BY config_key
`

func (q *Queries) GetAgentConfig(ctx context.Context, agentID pgtype.UUID) ([]AgentConfig, error) {
	rows, err := q.db.Query(ctx, getAgentConfig, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConfig{}
	for rows.Next() {
		var i AgentConfig
		if err := rows.Scan(
			&i.AgentID,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentConfigByKey = `-- name: GetAgentConfigByKey :one
SELECT agent_id, config_key, config_value, updated_at
FROM agent_config
WHERE agent_id = $1 AND config_key = $2
`

type GetAgentConfigByKeyParams struct {
	AgentID   pgtype.UUID `json:"agent_id"`
	ConfigKey string      `json:"config_key"`
}

func (q *Queries) GetAgentConfigByKey(ctx context.Context, arg GetAgentConfigByKeyParams) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, getAgentConfigByKey, arg.AgentID, arg.ConfigKey)
	var i AgentConfig
	err := row.Scan(
		&i.AgentID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.UpdatedAt,
	)
	return i, err
}

const setAgentConfig = `-- name: SetAgentConfig :exec
INSERT INTO agent_config (agent_id, config_key, config_value, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (agent_id, config_key)
DO UPDATE SET config_value = $3, updated_at = NOW()
`

type SetAgentConfigParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	ConfigKey   string      `json:"config_key"`
	ConfigValue []byte      `json:"config_value"`
}

func (q *Queries) SetAgentConfig(ctx context.Context, arg SetAgentConfigParams) error {
	_, err := q.db.Exec(ctx, setAgentConfig, arg.AgentID, arg.ConfigKey, arg.ConfigValue)
	return err
}
