// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentExists = `-- name: AgentExists :one
SELECT EXISTS(SELECT 1 FROM agents WHERE id = $1)
`

func (q *Queries) AgentExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, agentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, secret_hash, hostname, os, platform, arch, cpu_model, cpu_cores, ram_total, registered_at, last_seen, ip_address
FROM agents WHERE id = $1
`

type GetAgentRow struct {
	ID           pgtype.UUID        `json:"id"`
	SecretHash   string             `json:"secret_hash"`
	Hostname     string             `json:"hostname"`
	Os           pgtype.Text        `json:"os"`
	Platform     pgtype.Text        `json:"platform"`
	Arch         pgtype.Text        `json:"arch"`
	CpuModel     pgtype.Text        `json:"cpu_model"`
	CpuCores     pgtype.Int4        `json:"cpu_cores"`
	RamTotal     pgtype.Int8        `json:"ram_total"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	IpAddress    pgtype.Text        `json:"ip_address"`
}

func (q *Queries) GetAgent(ctx context.Context, id pgtype.UUID) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.SecretHash,
		&i.Hostname,
		&i.Os,
		&i.Platform,
		&i.Arch,
		&i.CpuModel,
		&i.CpuCores,
		&i.RamTotal,
		&i.RegisteredAt,
		&i.LastSeen,
		&i.IpAddress,
	)
	return i, err
}

const getAgentSecret = `-- name: GetAgentSecret :one
SELECT secret_hash FROM agents WHERE id = $1
`

func (q *Queries) GetAgentSecret(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAgentSecret, id)
	var secret_hash string
	err := row.Scan(&secret_hash)
	return secret_hash, err
}

const getAgentSecretSHA256 = `-- name: GetAgentSecretSHA256 :one
SELECT secret_sha256 FROM agents WHERE id = $1
`

func (q *Queries) GetAgentSecretSHA256(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAgentSecretSHA256, id)
	var secret_sha256 []byte
	err := row.Scan(&secret_sha256)
	return secret_sha256, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, hostname, os, platform, arch, cpu_cores, ram_total, registered_at, last_seen
FROM agents
ORDER BY hostname
`

type ListAgentsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Hostname     string             `json:"hostname"`
	Os           pgtype.Text        `json:"os"`
	Platform     pgtype.Text        `json:"platform"`
	Arch         pgtype.Text        `json:"arch"`
	CpuCores     pgtype.Int4        `json:"cpu_cores"`
	RamTotal     pgtype.Int8        `json:"ram_total"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
}

func (q *Queries) ListAgents(ctx context.Context) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.Os,
			&i.Platform,
			&i.Arch,
			&i.CpuCores,
			&i.RamTotal,
			&i.RegisteredAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOfflineAgents = `-- name: PurgeOfflineAgents :execrows
DELETE FROM agents
WHERE last_seen < NOW() - INTERVAL '7 days'
    OR last_seen IS NULL
`

func (q *Queries) PurgeOfflineAgents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOfflineAgents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerAgent = `-- name: RegisterAgent :exec
INSERT INTO agents (id, secret_hash, secret_sha256, hostname, os, platform, arch, cpu_model, cpu_cores, ram_total, ip_address, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type RegisterAgentParams struct {
	ID           pgtype.UUID `json:"id"`
	SecretHash   string      `json:"secret_hash"`
	SecretSha256 []byte      `json:"secret_sha256"`
	Hostname     string      `json:"hostname"`
	Os           pgtype.Text `json:"os"`
	Platform     pgtype.Text `json:"platform"`
	Arch         pgtype.Text `json:"arch"`
	CpuModel     pgtype.Text `json:"cpu_model"`
	CpuCores     pgtype.Int4 `json:"cpu_cores"`
	RamTotal     pgtype.Int8 `json:"ram_total"`
	IpAddress    pgtype.Text `json:"ip_address"`
	Version      string      `json:"version"`
}

func (q *Queries) RegisterAgent(ctx context.Context, arg RegisterAgentParams) error {
	_, err := q.db.Exec(ctx, registerAgent,
		arg.ID,
		arg.SecretHash,
		arg.SecretSha256,
		arg.Hostname,
		arg.Os,
		arg.Platform,
		arg.Arch,
		arg.CpuModel,
		arg.CpuCores,
		arg.RamTotal,
		arg.IpAddress,
		arg.Version,
	)
	return err
}

const setAgentSecretSHA256 = `-- name: SetAgentSecretSHA256 :exec
UPDATE agents SET secret_sha256 = $2 WHERE id = $1
`

type SetAgentSecretSHA256Params struct {
	ID           pgtype.UUID `json:"id"`
	SecretSha256 []byte      `json:"secret_sha256"`
}

func (q *Queries) SetAgentSecretSHA256(ctx context.Context, arg SetAgentSecretSHA256Params) error {
	_, err := q.db.Exec(ctx, setAgentSecretSHA256, arg.ID, arg.SecretSha256)
	return err
}

const touchLastSeen = `-- name: TouchLastSeen :exec
UPDATE agents SET last_seen = NOW() WHERE id = $1
`

func (q *Queries) TouchLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchLastSeen, id)
	return err
}

const touchLastSeenIfStale = `-- name: TouchLastSeenIfStale :exec
UPDATE agents
SET last_seen = NOW(), ip_address = $2
WHERE id = $1
    AND (last_seen IS NULL OR last_seen < NOW() - INTERVAL '60 seconds')
`

type TouchLastSeenIfStaleParams struct {
	ID        pgtype.UUID `json:"id"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) TouchLastSeenIfStale(ctx context.Context, arg TouchLastSeenIfStaleParams) error {
	_, err := q.db.Exec(ctx, touchLastSeenIfStale, arg.ID, arg.IpAddress)
	return err
}

const updateAgentInfo = `-- name: UpdateAgentInfo :exec
UPDATE agents
SET hostname = $2, os = $3, platform = $4, arch = $5, cpu_model = $6, cpu_cores = $7, ram_total = $8, last_seen = NOW()
WHERE id = $1
`

type UpdateAgentInfoParams struct {
	ID       pgtype.UUID `json:"id"`
	Hostname string      `json:"hostname"`
	Os       pgtype.Text `json:"os"`
	Platform pgtype.Text `json:"platform"`
	Arch     pgtype.Text `json:"arch"`
	CpuModel pgtype.Text `json:"cpu_model"`
	CpuCores pgtype.Int4 `json:"cpu_cores"`
	RamTotal pgtype.Int8 `json:"ram_total"`
}

func (q *Queries) UpdateAgentInfo(ctx context.Context, arg UpdateAgentInfoParams) error {
	_, err := q.db.Exec(ctx, updateAgentInfo,
		arg.ID,
		arg.Hostname,
		arg.Os,
		arg.Platform,
		arg.Arch,
		arg.CpuModel,
		arg.CpuCores,
		arg.RamTotal,
	)
	return err
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE agents SET last_seen = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastSeen, id)
	return err
}
