// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_version.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateAgentVersion = `-- name: UpdateAgentVersion :exec
UPDATE agents
SET version = $1
WHERE id = $2
    AND (version IS DISTINCT FROM $1)
`

type UpdateAgentVersionParams struct {
	Version string      `json:"version"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentVersion(ctx context.Context, arg UpdateAgentVersionParams) error {
	_, err := q.db.Exec(ctx, updateAgentVersion, arg.Version, arg.ID)
	return err
}
