// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelToRule = `-- name: AddChannelToRule :exec
INSERT INTO alert_rule_channels (rule_id, channel_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddChannelToRuleParams struct {
	RuleID    pgtype.UUID `json:"rule_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

func (q *Queries) AddChannelToRule(ctx context.Context, arg AddChannelToRuleParams) error {
	_, err := q.db.Exec(ctx, addChannelToRule, arg.RuleID, arg.ChannelID)
	return err
}

const createAlertChannel = `-- name: CreateAlertChannel :one
INSERT INTO alert_channels (name, type, config)
VALUES ($1, $2, $3)
RETURNING id, name, type, config, created_at
`

type CreateAlertChannelParams struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Config []byte `json:"config"`
}

func (q *Queries) CreateAlertChannel(ctx context.Context, arg CreateAlertChannelParams) (AlertChannel, error) {
	row := q.db.QueryRow(ctx, createAlertChannel, arg.Name, arg.Type, arg.Config)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const createAlertEvent = `-- name: CreateAlertEvent :one
INSERT INTO alert_events (rule_id, agent_id, condition_snapshot, last_notified_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, rule_id, agent_id, fired_at, resolved_at, last_notified_at, condition_snapshot
`

type CreateAlertEventParams struct {
	RuleID            pgtype.UUID `json:"rule_id"`
	AgentID           pgtype.UUID `json:"agent_id"`
	ConditionSnapshot []byte      `json:"condition_snapshot"`
}

func (q *Queries) CreateAlertEvent(ctx context.Context, arg CreateAlertEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, createAlertEvent, arg.RuleID, arg.AgentID, arg.ConditionSnapshot)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.AgentID,
		&i.FiredAt,
		&i.ResolvedAt,
		&i.LastNotifiedAt,
		&i.ConditionSnapshot,
	)
	return i, err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (name, enabled, scope, agent_id, condition_type, condition_params, cooldown_seconds)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, enabled, scope, agent_id, condition_type, condition_params, cooldown_seconds, created_at, updated_at
`

type CreateAlertRuleParams struct {
	Name            string      `json:"name"`
	Enabled         bool        `json:"enabled"`
	Scope           string      `json:"scope"`
	AgentID         pgtype.UUID `json:"agent_id"`
	ConditionType   string      `json:"condition_type"`
	ConditionParams []byte      `json:"condition_params"`
	CooldownSeconds int32       `json:"cooldown_seconds"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.Name,
		arg.Enabled,
		arg.Scope,
		arg.AgentID,
		arg.ConditionType,
		arg.ConditionParams,
		arg.CooldownSeconds,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Scope,
		&i.AgentID,
		&i.ConditionType,
		&i.ConditionParams,
		&i.CooldownSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlertChannel = `-- name: DeleteAlertChannel :exec
DELETE FROM alert_channels WHERE id = $1
`

func (q *Queries) DeleteAlertChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertChannel, id)
	return err
}

const deleteAlertRule = `-- name: DeleteAlertRule :exec
DELETE FROM alert_rules WHERE id = $1
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertRule, id)
	return err
}

const deleteChannelsForRule = `-- name: DeleteChannelsForRule :exec
DELETE FROM alert_rule_channels WHERE rule_id = $1
`

func (q *Queries) DeleteChannelsForRule(ctx context.Context, ruleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannelsForRule, ruleID)
	return err
}

const getActiveEvent = `-- name: GetActiveEvent :one
SELECT id, rule_id, agent_id, fired_at, resolved_at, last_notified_at, condition_snapshot FROM alert_events
WHERE rule_id = $1
  AND agent_id = $2
  AND resolved_at IS NULL
LIMIT 1
`

type GetActiveEventParams struct {
	RuleID  pgtype.UUID `json:"rule_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

// Returns the open (unresolved) event (if any) for a rule+agent pair.
func (q *Queries) GetActiveEvent(ctx context.Context, arg GetActiveEventParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, getActiveEvent, arg.RuleID, arg.AgentID)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.AgentID,
		&i.FiredAt,
		&i.ResolvedAt,
		&i.LastNotifiedAt,
		&i.ConditionSnapshot,
	)
	return i, err
}

const getAlertChannel = `-- name: GetAlertChannel :one
SELECT id, name, type, config, created_at FROM alert_channels
WHERE id = $1
`

func (q *Queries) GetAlertChannel(ctx context.Context, id pgtype.UUID) (AlertChannel, error) {
	row := q.db.QueryRow(ctx, getAlertChannel, id)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, name, enabled, scope, agent_id, condition_type, condition_params, cooldown_seconds, created_at, updated_at FROM alert_rules WHERE id = $1
`

func (q *Queries) GetAlertRule(ctx context.Context, id pgtype.UUID) (AlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRule, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Scope,
		&i.AgentID,
		&i.ConditionType,
		&i.ConditionParams,
		&i.CooldownSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastEventForRule = `-- name: GetLastEventForRule :one
SELECT id, rule_id, agent_id, fired_at, resolved_at, last_notified_at, condition_snapshot FROM alert_events
WHERE rule_id = $1
  AND agent_id = $2
ORDER BY fired_at DESC
LIMIT 1
`

type GetLastEventForRuleParams struct {
	RuleID  pgtype.UUID `json:"rule_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

// Used for cooldown check: returns the most recently fired event
// regardless of resolved state.
func (q *Queries) GetLastEventForRule(ctx context.Context, arg GetLastEventForRuleParams) (AlertEvent, error) {
	row := q.db.QueryRow(ctx, getLastEventForRule, arg.RuleID, arg.AgentID)
	var i AlertEvent
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.AgentID,
		&i.FiredAt,
		&i.ResolvedAt,
		&i.LastNotifiedAt,
		&i.ConditionSnapshot,
	)
	return i, err
}

const listActiveAlertEvents = `-- name: ListActiveAlertEvents :many
SELECT
	ae.id, ae.rule_id, ae.agent_id, ae.fired_at, ae.resolved_at, ae.last_notified_at, ae.condition_snapshot,
	ar.name AS rule_name,
	ar.condition_type,
	a.hostname
FROM alert_events ae
JOIN alert_rules ar ON ar.id = ae.rule_id
JOIN agents a ON a.id = ae.agent_id
WHERE ae.resolved_at IS NULL
ORDER BY ae.fired_at DESC
`

type ListActiveAlertEventsRow struct {
	ID                pgtype.UUID        `json:"id"`
	RuleID            pgtype.UUID        `json:"rule_id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	FiredAt           pgtype.Timestamptz `json:"fired_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	LastNotifiedAt    pgtype.Timestamptz `json:"last_notified_at"`
	ConditionSnapshot []byte             `json:"condition_snapshot"`
	RuleName          string             `json:"rule_name"`
	ConditionType     string             `json:"condition_type"`
	Hostname          string             `json:"hostname"`
}

func (q *Queries) ListActiveAlertEvents(ctx context.Context) ([]ListActiveAlertEventsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlertEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAlertEventsRow{}
	for rows.Next() {
		var i ListActiveAlertEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.AgentID,
			&i.FiredAt,
			&i.ResolvedAt,
			&i.LastNotifiedAt,
			&i.ConditionSnapshot,
			&i.RuleName,
			&i.ConditionType,
			&i.Hostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertChannels = `-- name: ListAlertChannels :many
SELECT id, name, type, config, created_at FROM alert_channels
ORDER BY name
`

func (q *Queries) ListAlertChannels(ctx context.Context) ([]AlertChannel, error) {
	rows, err := q.db.Query(ctx, listAlertChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertChannel{}
	for rows.Next() {
		var i AlertChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertEventHistory = `-- name: ListAlertEventHistory :many
SELECT
	ae.id, ae.rule_id, ae.agent_id, ae.fired_at, ae.resolved_at, ae.last_notified_at, ae.condition_snapshot,
	ar.name AS rule_name,
	ar.condition_type,
	a.hostname
FROM alert_events ae
JOIN alert_rules ar ON ar.id = ae.rule_id
JOIN agents a ON a.id = ae.agent_id
ORDER BY ae.fired_at DESC
LIMIT $1 OFFSET $2
`

type ListAlertEventHistoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAlertEventHistoryRow struct {
	ID                pgtype.UUID        `json:"id"`
	RuleID            pgtype.UUID        `json:"rule_id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	FiredAt           pgtype.Timestamptz `json:"fired_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	LastNotifiedAt    pgtype.Timestamptz `json:"last_notified_at"`
	ConditionSnapshot []byte             `json:"condition_snapshot"`
	RuleName          string             `json:"rule_name"`
	ConditionType     string             `json:"condition_type"`
	Hostname          string             `json:"hostname"`
}

func (q *Queries) ListAlertEventHistory(ctx context.Context, arg ListAlertEventHistoryParams) ([]ListAlertEventHistoryRow, error) {
	rows, err := q.db.Query(ctx, listAlertEventHistory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertEventHistoryRow{}
	for rows.Next() {
		var i ListAlertEventHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.AgentID,
			&i.FiredAt,
			&i.ResolvedAt,
			&i.LastNotifiedAt,
			&i.ConditionSnapshot,
			&i.RuleName,
			&i.ConditionType,
			&i.Hostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertEventsByAgent = `-- name: ListAlertEventsByAgent :many
SELECT
	ae.id, ae.rule_id, ae.agent_id, ae.fired_at, ae.resolved_at, ae.last_notified_at, ae.condition_snapshot,
	ar.name AS rule_name,
	ar.condition_type
FROM alert_events ae
JOIN alert_rules ar ON ar.id = ae.rule_id
WHERE ae.agent_id = $3
ORDER BY ae.fired_at DESC
LIMIT $1 OFFSET $2
`

type ListAlertEventsByAgentParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	AgentID pgtype.UUID `json:"agent_id"`
}

type ListAlertEventsByAgentRow struct {
	ID                pgtype.UUID        `json:"id"`
	RuleID            pgtype.UUID        `json:"rule_id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	FiredAt           pgtype.Timestamptz `json:"fired_at"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	LastNotifiedAt    pgtype.Timestamptz `json:"last_notified_at"`
	ConditionSnapshot []byte             `json:"condition_snapshot"`
	RuleName          string             `json:"rule_name"`
	ConditionType     string             `json:"condition_type"`
}

func (q *Queries) ListAlertEventsByAgent(ctx context.Context, arg ListAlertEventsByAgentParams) ([]ListAlertEventsByAgentRow, error) {
	rows, err := q.db.Query(ctx, listAlertEventsByAgent, arg.Limit, arg.Offset, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertEventsByAgentRow{}
	for rows.Next() {
		var i ListAlertEventsByAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.AgentID,
			&i.FiredAt,
			&i.ResolvedAt,
			&i.LastNotifiedAt,
			&i.ConditionSnapshot,
			&i.RuleName,
			&i.ConditionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT id, name, enabled, scope, agent_id, condition_type, condition_params, cooldown_seconds, created_at, updated_at FROM alert_rules
ORDER BY created_at DESC
`

func (q *Queries) ListAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Scope,
			&i.AgentID,
			&i.ConditionType,
			&i.ConditionParams,
			&i.CooldownSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveEvents = `-- name: ListAllActiveEvents :many
SELECT id, rule_id, agent_id, fired_at, resolved_at, last_notified_at, condition_snapshot
FROM alert_events
WHERE resolved_at IS NULL
`

// Bulk-load every unresolved event so the evaluator can key them in Go by
// rule_id + agent_id instead of issuing GetActiveEvent per rule/agent pair.
func (q *Queries) ListAllActiveEvents(ctx context.Context) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAllActiveEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.AgentID,
			&i.FiredAt,
			&i.ResolvedAt,
			&i.LastNotifiedAt,
			&i.ConditionSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForRule = `-- name: ListChannelsForRule :many
SELECT ac.id, ac.name, ac.type, ac.config, ac.created_at
FROM alert_channels ac
JOIN alert_rule_channels arc ON arc.channel_id = ac.id
WHERE arc.rule_id = $1
ORDER BY ac.name
`

func (q *Queries) ListChannelsForRule(ctx context.Context, ruleID pgtype.UUID) ([]AlertChannel, error) {
	rows, err := q.db.Query(ctx, listChannelsForRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertChannel{}
	for rows.Next() {
		var i AlertChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRules = `-- name: ListEnabledAlertRules :many
SELECT id, name, enabled, scope, agent_id, condition_type, condition_params, cooldown_seconds, created_at, updated_at FROM alert_rules
WHERE enabled = TRUE
ORDER BY scope DESC, created_at DESC
`

func (q *Queries) ListEnabledAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Scope,
			&i.AgentID,
			&i.ConditionType,
			&i.ConditionParams,
			&i.CooldownSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLastEventPerRuleAgent = `-- name: ListLastEventPerRuleAgent :many
SELECT DISTINCT ON (rule_id, agent_id)
    id, rule_id, agent_id, fired_at, resolved_at, last_notified_at, condition_snapshot
FROM alert_events
ORDER BY rule_id, agent_id, fired_at DESC
`

// Bulk-load the most recent event (resolved or not) for every rule+agent pair,
// for cooldown checks. DISTINCT ON returns one row per (rule_id, agent_id),
// ordered so the newest fired_at wins.
func (q *Queries) ListLastEventPerRuleAgent(ctx context.Context) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listLastEventPerRuleAgent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertEvent{}
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.AgentID,
			&i.FiredAt,
			&i.ResolvedAt,
			&i.LastNotifiedAt,
			&i.ConditionSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannelFromRule = `-- name: RemoveChannelFromRule :exec
DELETE FROM alert_rule_channels
WHERE rule_id = $1 AND channel_id = $2
`

type RemoveChannelFromRuleParams struct {
	RuleID    pgtype.UUID `json:"rule_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

func (q *Queries) RemoveChannelFromRule(ctx context.Context, arg RemoveChannelFromRuleParams) error {
	_, err := q.db.Exec(ctx, removeChannelFromRule, arg.RuleID, arg.ChannelID)
	return err
}

const resolveAlertEvent = `-- name: ResolveAlertEvent :exec
UPDATE alert_events
SET resolved_at = NOW()
WHERE rule_id = $1
  AND agent_id = $2
  AND resolved_at IS NULL
`

type ResolveAlertEventParams struct {
	RuleID  pgtype.UUID `json:"rule_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) ResolveAlertEvent(ctx context.Context, arg ResolveAlertEventParams) error {
	_, err := q.db.Exec(ctx, resolveAlertEvent, arg.RuleID, arg.AgentID)
	return err
}

const setAlertRuleEnabled = `-- name: SetAlertRuleEnabled :one
UPDATE alert_rules
SET	enabled = $1,
	updated_at = NOW()
WHERE id = $2
RETURNING id, name, enabled, scope, agent_id, condition_type, condition_params, cooldown_seconds, created_at, updated_at
`

type SetAlertRuleEnabledParams struct {
	Enabled bool        `json:"enabled"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) SetAlertRuleEnabled(ctx context.Context, arg SetAlertRuleEnabledParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, setAlertRuleEnabled, arg.Enabled, arg.ID)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Scope,
		&i.AgentID,
		&i.ConditionType,
		&i.ConditionParams,
		&i.CooldownSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAlertEventNotified = `-- name: TouchAlertEventNotified :exec
UPDATE alert_events
SET last_notified_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchAlertEventNotified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAlertEventNotified, id)
	return err
}

const updateAlertChannel = `-- name: UpdateAlertChannel :one
UPDATE alert_channels
SET	name = $1,
	type = $2,
	config = $3
WHERE id = $4
RETURNING id, name, type, config, created_at
`

type UpdateAlertChannelParams struct {
	Name   string      `json:"name"`
	Type   string      `json:"type"`
	Config []byte      `json:"config"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAlertChannel(ctx context.Context, arg UpdateAlertChannelParams) (AlertChannel, error) {
	row := q.db.QueryRow(ctx, updateAlertChannel,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.ID,
	)
	var i AlertChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET	name = $1,
	enabled = $2,
	condition_params = $3,
	cooldown_seconds = $4,
	updated_at = NOW()
WHERE id = $5
RETURNING id, name, enabled, scope, agent_id, condition_type, condition_params, cooldown_seconds, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	Name            string      `json:"name"`
	Enabled         bool        `json:"enabled"`
	ConditionParams []byte      `json:"condition_params"`
	CooldownSeconds int32       `json:"cooldown_seconds"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.Name,
		arg.Enabled,
		arg.ConditionParams,
		arg.CooldownSeconds,
		arg.ID,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Scope,
		&i.AgentID,
		&i.ConditionType,
		&i.ConditionParams,
		&i.CooldownSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
