// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: current_state.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleProcesses = `-- name: DeleteStaleProcesses :exec
DELETE FROM current_processes
WHERE agent_id = $1 AND updated_at < $2
`

type DeleteStaleProcessesParams struct {
	AgentID   pgtype.UUID        `json:"agent_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeleteStaleProcesses(ctx context.Context, arg DeleteStaleProcessesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleProcesses, arg.AgentID, arg.UpdatedAt)
	return err
}

const getApplications = `-- name: GetApplications :many
SELECT agent_id, name, version, updated_at
FROM current_applications
WHERE agent_id = $1
ORDER BY name
`

func (q *Queries) GetApplications(ctx context.Context, agentID pgtype.UUID) ([]CurrentApplication, error) {
	rows, err := q.db.Query(ctx, getApplications, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentApplication{}
	for rows.Next() {
		var i CurrentApplication
		if err := rows.Scan(
			&i.AgentID,
			&i.Name,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessesByCPU = `-- name: GetProcessesByCPU :many
SELECT agent_id, pid, name, cpu_percent, mem_percent, mem_rss, status, threads, updated_at
FROM current_processes
WHERE agent_id = $1
ORDER BY cpu_percent DESC
LIMIT $2
`

type GetProcessesByCPUParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetProcessesByCPU(ctx context.Context, arg GetProcessesByCPUParams) ([]CurrentProcess, error) {
	rows, err := q.db.Query(ctx, getProcessesByCPU, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentProcess{}
	for rows.Next() {
		var i CurrentProcess
		if err := rows.Scan(
			&i.AgentID,
			&i.Pid,
			&i.Name,
			&i.CpuPercent,
			&i.MemPercent,
			&i.MemRss,
			&i.Status,
			&i.Threads,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessesByMemory = `-- name: GetProcessesByMemory :many
SELECT agent_id, pid, name, cpu_percent, mem_percent, mem_rss, status, threads, updated_at
FROM current_processes
WHERE agent_id = $1
ORDER BY mem_rss DESC
LIMIT $2
`

type GetProcessesByMemoryParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetProcessesByMemory(ctx context.Context, arg GetProcessesByMemoryParams) ([]CurrentProcess, error) {
	rows, err := q.db.Query(ctx, getProcessesByMemory, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentProcess{}
	for rows.Next() {
		var i CurrentProcess
		if err := rows.Scan(
			&i.AgentID,
			&i.Pid,
			&i.Name,
			&i.CpuPercent,
			&i.MemPercent,
			&i.MemRss,
			&i.Status,
			&i.Threads,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServices = `-- name: GetServices :many
SELECT agent_id, name, status, sub_status, updated_at
FROM current_services
WHERE agent_id = $1
ORDER BY name
`

func (q *Queries) GetServices(ctx context.Context, agentID pgtype.UUID) ([]CurrentService, error) {
	rows, err := q.db.Query(ctx, getServices, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentService{}
	for rows.Next() {
		var i CurrentService
		if err := rows.Scan(
			&i.AgentID,
			&i.Name,
			&i.Status,
			&i.SubStatus,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApplication = `-- name: UpsertApplication :exec
INSERT INTO current_applications (agent_id, name, version, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (agent_id, name) DO UPDATE
SET version = EXCLUDED.version,
    updated_at = NOW()
`

type UpsertApplicationParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Name    string      `json:"name"`
	Version pgtype.Text `json:"version"`
}

func (q *Queries) UpsertApplication(ctx context.Context, arg UpsertApplicationParams) error {
	_, err := q.db.Exec(ctx, upsertApplication, arg.AgentID, arg.Name, arg.Version)
	return err
}

const upsertProcess = `-- name: UpsertProcess :exec
INSERT INTO current_processes (agent_id, pid, name, cpu_percent, mem_percent, mem_rss, status, threads, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (agent_id, pid) DO UPDATE
SET name = EXCLUDED.name,
    cpu_percent = EXCLUDED.cpu_percent,
    mem_percent = EXCLUDED.mem_percent,
    mem_rss = EXCLUDED.mem_rss,
    status = EXCLUDED.status,
    threads = EXCLUDED.threads,
    updated_at = NOW()
`

type UpsertProcessParams struct {
	AgentID    pgtype.UUID   `json:"agent_id"`
	Pid        int32         `json:"pid"`
	Name       pgtype.Text   `json:"name"`
	CpuPercent pgtype.Float8 `json:"cpu_percent"`
	MemPercent pgtype.Float8 `json:"mem_percent"`
	MemRss     pgtype.Int8   `json:"mem_rss"`
	Status     pgtype.Text   `json:"status"`
	Threads    pgtype.Int4   `json:"threads"`
}

func (q *Queries) UpsertProcess(ctx context.Context, arg UpsertProcessParams) error {
	_, err := q.db.Exec(ctx, upsertProcess,
		arg.AgentID,
		arg.Pid,
		arg.Name,
		arg.CpuPercent,
		arg.MemPercent,
		arg.MemRss,
		arg.Status,
		arg.Threads,
	)
	return err
}

const upsertService = `-- name: UpsertService :exec
INSERT INTO current_services (agent_id, name, status, sub_status, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (agent_id, name) DO UPDATE
SET status = EXCLUDED.status,
    sub_status = EXCLUDED.sub_status,
    updated_at = NOW()
`

type UpsertServiceParams struct {
	AgentID   pgtype.UUID `json:"agent_id"`
	Name      string      `json:"name"`
	Status    pgtype.Text `json:"status"`
	SubStatus pgtype.Text `json:"sub_status"`
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) error {
	_, err := q.db.Exec(ctx, upsertService,
		arg.AgentID,
		arg.Name,
		arg.Status,
		arg.SubStatus,
	)
	return err
}
