// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: current_state.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleProcesses = `-- name: DeleteStaleProcesses :exec
DELETE FROM current_processes
WHERE agent_id = $1 AND updated_at < $2
`

type DeleteStaleProcessesParams struct {
	AgentID   pgtype.UUID        `json:"agent_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DeleteStaleProcesses(ctx context.Context, arg DeleteStaleProcessesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleProcesses, arg.AgentID, arg.UpdatedAt)
	return err
}

const getAllServices = `-- name: GetAllServices :many
SELECT agent_id, name, status, sub_status, updated_at
FROM current_services
ORDER BY agent_id, name
`

// Bulk-load current services across the whole fleet so the evaluator can build
// an agent_id -> services map in one query instead of GetServices per agent.
func (q *Queries) GetAllServices(ctx context.Context) ([]CurrentService, error) {
	rows, err := q.db.Query(ctx, getAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentService{}
	for rows.Next() {
		var i CurrentService
		if err := rows.Scan(
			&i.AgentID,
			&i.Name,
			&i.Status,
			&i.SubStatus,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplications = `-- name: GetApplications :many
SELECT agent_id, name, version, updated_at
FROM current_applications
WHERE agent_id = $1
ORDER BY name
`

func (q *Queries) GetApplications(ctx context.Context, agentID pgtype.UUID) ([]CurrentApplication, error) {
	rows, err := q.db.Query(ctx, getApplications, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentApplication{}
	for rows.Next() {
		var i CurrentApplication
		if err := rows.Scan(
			&i.AgentID,
			&i.Name,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessesByCPU = `-- name: GetProcessesByCPU :many
SELECT agent_id, pid, name, cpu_percent, mem_percent, mem_rss, status, threads, updated_at
FROM current_processes
WHERE agent_id = $1
ORDER BY cpu_percent DESC
LIMIT $2
`

type GetProcessesByCPUParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetProcessesByCPU(ctx context.Context, arg GetProcessesByCPUParams) ([]CurrentProcess, error) {
	rows, err := q.db.Query(ctx, getProcessesByCPU, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentProcess{}
	for rows.Next() {
		var i CurrentProcess
		if err := rows.Scan(
			&i.AgentID,
			&i.Pid,
			&i.Name,
			&i.CpuPercent,
			&i.MemPercent,
			&i.MemRss,
			&i.Status,
			&i.Threads,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessesByMemory = `-- name: GetProcessesByMemory :many
SELECT agent_id, pid, name, cpu_percent, mem_percent, mem_rss, status, threads, updated_at
FROM current_processes
WHERE agent_id = $1
ORDER BY mem_rss DESC
LIMIT $2
`

type GetProcessesByMemoryParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetProcessesByMemory(ctx context.Context, arg GetProcessesByMemoryParams) ([]CurrentProcess, error) {
	rows, err := q.db.Query(ctx, getProcessesByMemory, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentProcess{}
	for rows.Next() {
		var i CurrentProcess
		if err := rows.Scan(
			&i.AgentID,
			&i.Pid,
			&i.Name,
			&i.CpuPercent,
			&i.MemPercent,
			&i.MemRss,
			&i.Status,
			&i.Threads,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServices = `-- name: GetServices :many
SELECT agent_id, name, status, sub_status, updated_at
FROM current_services
WHERE agent_id = $1
ORDER BY name
`

func (q *Queries) GetServices(ctx context.Context, agentID pgtype.UUID) ([]CurrentService, error) {
	rows, err := q.db.Query(ctx, getServices, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrentService{}
	for rows.Next() {
		var i CurrentService
		if err := rows.Scan(
			&i.AgentID,
			&i.Name,
			&i.Status,
			&i.SubStatus,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdates = `-- name: GetUpdates :one
SELECT agent_id, pending_count, security_count, reboot_required, package_manager, updated_at
FROM current_updates
WHERE agent_id = $1
`

func (q *Queries) GetUpdates(ctx context.Context, agentID pgtype.UUID) (CurrentUpdate, error) {
	row := q.db.QueryRow(ctx, getUpdates, agentID)
	var i CurrentUpdate
	err := row.Scan(
		&i.AgentID,
		&i.PendingCount,
		&i.SecurityCount,
		&i.RebootRequired,
		&i.PackageManager,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertApplications = `-- name: UpsertApplications :exec
INSERT INTO current_applications (agent_id, name, version, updated_at)
SELECT DISTINCT ON (a.name) $1::uuid, a.name, a.version, NOW()
FROM (
    SELECT  unnest($2::text[]) AS name,
            unnest($3::text[]) AS version
) AS a
ON CONFLICT (agent_id, name) DO UPDATE
SET version = EXCLUDED.version,
    updated_at = NOW()
`

type UpsertApplicationsParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	Names    []string    `json:"names"`
	Versions []string    `json:"versions"`
}

// One statement per application list; DISTINCT ON as in UpsertProcesses
func (q *Queries) UpsertApplications(ctx context.Context, arg UpsertApplicationsParams) error {
	_, err := q.db.Exec(ctx, upsertApplications, arg.AgentID, arg.Names, arg.Versions)
	return err
}

const upsertProcesses = `-- name: UpsertProcesses :exec
INSERT INTO current_processes (agent_id, pid, name, cpu_percent, mem_percent, mem_rss, status, threads, updated_at)
SELECT DISTINCT ON (p.pid) $1::uuid, p.pid, p.name, p.cpu_percent, p.mem_percent, p.mem_rss, p.status, p.threads, NOW()
FROM (
    SELECT  unnest($2::integer[]) AS pid,
            unnest($3::text[]) AS name,
            unnest($4::double precision[]) AS cpu_percent,
            unnest($5::double precision[]) AS mem_percent,
            unnest($6::bigint[]) AS mem_rss,
            unnest($7::text[]) AS status,
            unnest($8::integer[]) AS threads
) AS p
ON CONFLICT (agent_id, pid) DO UPDATE
SET name = EXCLUDED.name,
    cpu_percent = EXCLUDED.cpu_percent,
    mem_percent = EXCLUDED.mem_percent,
    mem_rss = EXCLUDED.mem_rss,
    status = EXCLUDED.status,
    threads = EXCLUDED.threads,
    updated_at = NOW()
`

type UpsertProcessesParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	Pids        []int32     `json:"pids"`
	Names       []string    `json:"names"`
	CpuPercents []float64   `json:"cpu_percents"`
	MemPercents []float64   `json:"mem_percents"`
	MemRss      []int64     `json:"mem_rss"`
	Statuses    []string    `json:"statuses"`
	Threads     []int32     `json:"threads"`
}

// One statement per process list. DISTINCT ON drops a repeated pid, which ON CONFLICT DO UPDATE
// would reject, failing the batch on every retry.
func (q *Queries) UpsertProcesses(ctx context.Context, arg UpsertProcessesParams) error {
	_, err := q.db.Exec(ctx, upsertProcesses,
		arg.AgentID,
		arg.Pids,
		arg.Names,
		arg.CpuPercents,
		arg.MemPercents,
		arg.MemRss,
		arg.Statuses,
		arg.Threads,
	)
	return err
}

const upsertServices = `-- name: UpsertServices :exec
INSERT INTO current_services (agent_id, name, status, sub_status, updated_at)
SELECT DISTINCT ON (s.name) $1::uuid, s.name, s.status, s.sub_status, NOW()
FROM (
    SELECT  unnest($2::text[]) AS name,
            unnest($3::text[]) AS status,
            unnest($4::text[]) AS sub_status
) AS s
ON CONFLICT (agent_id, name) DO UPDATE
SET status = EXCLUDED.status,
    sub_status = EXCLUDED.sub_status,
    updated_at = NOW()
`

type UpsertServicesParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	Names       []string    `json:"names"`
	Statuses    []string    `json:"statuses"`
	SubStatuses []string    `json:"sub_statuses"`
}

// One statement per service list; DISTINCT ON as in UpsertProcesses
func (q *Queries) UpsertServices(ctx context.Context, arg UpsertServicesParams) error {
	_, err := q.db.Exec(ctx, upsertServices,
		arg.AgentID,
		arg.Names,
		arg.Statuses,
		arg.SubStatuses,
	)
	return err
}

const upsertUpdates = `-- name: UpsertUpdates :exec
INSERT INTO current_updates (agent_id, pending_count, security_count, reboot_required, package_manager, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (agent_id) DO UPDATE
SET pending_count = EXCLUDED.pending_count,
    security_count = EXCLUDED.security_count,
    reboot_required = EXCLUDED.reboot_required,
    package_manager = EXCLUDED.package_manager,
    updated_at = NOW()
`

type UpsertUpdatesParams struct {
	AgentID        pgtype.UUID `json:"agent_id"`
	PendingCount   int32       `json:"pending_count"`
	SecurityCount  int32       `json:"security_count"`
	RebootRequired bool        `json:"reboot_required"`
	PackageManager pgtype.Text `json:"package_manager"`
}

func (q *Queries) UpsertUpdates(ctx context.Context, arg UpsertUpdatesParams) error {
	_, err := q.db.Exec(ctx, upsertUpdates,
		arg.AgentID,
		arg.PendingCount,
		arg.SecurityCount,
		arg.RebootRequired,
		arg.PackageManager,
	)
	return err
}
