// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heatmap.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFleetHeatmap = `-- name: GetFleetHeatmap :many
WITH cpu_buckets AS (
    SELECT
        time_bucket('1 hour', c.time)::timestamptz AS bucket,
        agent_id,
        AVG(c.usage)::float8 AS value,
        'cpu'::text AS metric
    FROM metrics_cpu c
    WHERE c.time >= $1 AND c.time <= $2
    GROUP BY 1, 2
),
mem_buckets AS (
    SELECT
        time_bucket('1 hour', m.time)::timestamptz AS bucket,
        agent_id,
        AVG(m.ram_percent)::float8 AS value,
        'mem'::text AS metric
    FROM metrics_memory m
    WHERE m.time >= $1 AND m.time <= $2
    GROUP BY 1, 2
),
disk_buckets AS (
    SELECT
        time_bucket('1 hour', d.time)::timestamptz AS bucket,
        agent_id,
        MAX(d.used_percent)::float8 AS value,
        'disk'::text AS metric
    FROM metrics_disk d
    WHERE d.time >= $1 AND d.time <= $2
    GROUP BY 1, 2
)
SELECT bucket, agent_id, value, metric
FROM cpu_buckets
UNION ALL
SELECT bucket, agent_id, value, metric
FROM mem_buckets
UNION ALL
SELECT bucket, agent_id, value, metric
FROM disk_buckets
ORDER BY agent_id, metric, bucket ASC
`

type GetFleetHeatmapParams struct {
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetFleetHeatmapRow struct {
	Bucket  pgtype.Timestamptz `json:"bucket"`
	AgentID pgtype.UUID        `json:"agent_id"`
	Value   float64            `json:"value"`
	Metric  string             `json:"metric"`
}

func (q *Queries) GetFleetHeatmap(ctx context.Context, arg GetFleetHeatmapParams) ([]GetFleetHeatmapRow, error) {
	rows, err := q.db.Query(ctx, getFleetHeatmap, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFleetHeatmapRow{}
	for rows.Next() {
		var i GetFleetHeatmapRow
		if err := rows.Scan(
			&i.Bucket,
			&i.AgentID,
			&i.Value,
			&i.Metric,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
