// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics_read.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestCPU = `-- name: GetLatestCPU :many
SELECT time, agent_id, usage, core_usages, load_1m, load_5m, load_15m, iowait
FROM metrics_cpu
WHERE agent_id = $1 AND time > NOW() - $2::interval
ORDER BY time DESC
`

type GetLatestCPUParams struct {
	AgentID pgtype.UUID     `json:"agent_id"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) GetLatestCPU(ctx context.Context, arg GetLatestCPUParams) ([]MetricsCpu, error) {
	rows, err := q.db.Query(ctx, getLatestCPU, arg.AgentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsCpu{}
	for rows.Next() {
		var i MetricsCpu
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Usage,
			&i.CoreUsages,
			&i.Load1m,
			&i.Load5m,
			&i.Load15m,
			&i.Iowait,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestContainers = `-- name: GetLatestContainers :many
SELECT time, agent_id, container_id, name, image, state, source, kind, cpu_percent, cpu_cores, memory_bytes, memory_limit, net_rx_bytes, net_tx_bytes
FROM metrics_container
WHERE agent_id = $1 AND time > NOW() - $2::interval
ORDER BY time DESC
`

type GetLatestContainersParams struct {
	AgentID pgtype.UUID     `json:"agent_id"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) GetLatestContainers(ctx context.Context, arg GetLatestContainersParams) ([]MetricsContainer, error) {
	rows, err := q.db.Query(ctx, getLatestContainers, arg.AgentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsContainer{}
	for rows.Next() {
		var i MetricsContainer
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.ContainerID,
			&i.Name,
			&i.Image,
			&i.State,
			&i.Source,
			&i.Kind,
			&i.CpuPercent,
			&i.CpuCores,
			&i.MemoryBytes,
			&i.MemoryLimit,
			&i.NetRxBytes,
			&i.NetTxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDisk = `-- name: GetLatestDisk :many
SELECT time, agent_id, device, mountpoint, filesystem, disk_type, total_bytes, used_bytes, free_bytes, used_percent, inodes_total, inodes_used, inodes_percent
FROM metrics_disk
WHERE agent_id = $1 AND time > NOW() - $2::interval
ORDER BY time DESC
`

type GetLatestDiskParams struct {
	AgentID pgtype.UUID     `json:"agent_id"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) GetLatestDisk(ctx context.Context, arg GetLatestDiskParams) ([]MetricsDisk, error) {
	rows, err := q.db.Query(ctx, getLatestDisk, arg.AgentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsDisk{}
	for rows.Next() {
		var i MetricsDisk
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Device,
			&i.Mountpoint,
			&i.Filesystem,
			&i.DiskType,
			&i.TotalBytes,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.UsedPercent,
			&i.InodesTotal,
			&i.InodesUsed,
			&i.InodesPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDiskIO = `-- name: GetLatestDiskIO :many
SELECT time, agent_id, device, read_bytes, write_bytes, read_ops, write_ops, read_latency, write_latency, io_in_progress
FROM metrics_disk_io
WHERE agent_id = $1 AND time > NOW() - $2::interval
ORDER BY time DESC
`

type GetLatestDiskIOParams struct {
	AgentID pgtype.UUID     `json:"agent_id"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) GetLatestDiskIO(ctx context.Context, arg GetLatestDiskIOParams) ([]MetricsDiskIo, error) {
	rows, err := q.db.Query(ctx, getLatestDiskIO, arg.AgentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsDiskIo{}
	for rows.Next() {
		var i MetricsDiskIo
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Device,
			&i.ReadBytes,
			&i.WriteBytes,
			&i.ReadOps,
			&i.WriteOps,
			&i.ReadLatency,
			&i.WriteLatency,
			&i.IoInProgress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMemory = `-- name: GetLatestMemory :many
SELECT time, agent_id, ram_total, ram_used, ram_available, ram_percent, swap_total, swap_used, swap_percent
FROM metrics_memory
WHERE agent_id = $1 AND time > NOW() - $2::interval
ORDER BY time DESC
`

type GetLatestMemoryParams struct {
	AgentID pgtype.UUID     `json:"agent_id"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) GetLatestMemory(ctx context.Context, arg GetLatestMemoryParams) ([]MetricsMemory, error) {
	rows, err := q.db.Query(ctx, getLatestMemory, arg.AgentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsMemory{}
	for rows.Next() {
		var i MetricsMemory
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.RamTotal,
			&i.RamUsed,
			&i.RamAvailable,
			&i.RamPercent,
			&i.SwapTotal,
			&i.SwapUsed,
			&i.SwapPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestNetwork = `-- name: GetLatestNetwork :many
SELECT time, agent_id, interface, mac, mtu, speed, rx_bytes, rx_packets, rx_errors, rx_drops, tx_bytes, tx_packets, tx_errors, tx_drops
FROM metrics_network
WHERE agent_id = $1 AND time > NOW() - $2::interval
ORDER BY time DESC
`

type GetLatestNetworkParams struct {
	AgentID pgtype.UUID     `json:"agent_id"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) GetLatestNetwork(ctx context.Context, arg GetLatestNetworkParams) ([]MetricsNetwork, error) {
	rows, err := q.db.Query(ctx, getLatestNetwork, arg.AgentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsNetwork{}
	for rows.Next() {
		var i MetricsNetwork
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Interface,
			&i.Mac,
			&i.Mtu,
			&i.Speed,
			&i.RxBytes,
			&i.RxPackets,
			&i.RxErrors,
			&i.RxDrops,
			&i.TxBytes,
			&i.TxPackets,
			&i.TxErrors,
			&i.TxDrops,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSystem = `-- name: GetLatestSystem :one
SELECT time, agent_id, uptime, process_count, user_count, boot_time
FROM metrics_system
WHERE agent_id = $1
ORDER BY time DESC
LIMIT 1
`

func (q *Queries) GetLatestSystem(ctx context.Context, agentID pgtype.UUID) (MetricsSystem, error) {
	row := q.db.QueryRow(ctx, getLatestSystem, agentID)
	var i MetricsSystem
	err := row.Scan(
		&i.Time,
		&i.AgentID,
		&i.Uptime,
		&i.ProcessCount,
		&i.UserCount,
		&i.BootTime,
	)
	return i, err
}

const getLatestTemperature = `-- name: GetLatestTemperature :many
SELECT time, agent_id, sensor, temperature, max_temp
FROM metrics_temperature
WHERE agent_id = $1 AND time > NOW() - $2::interval
ORDER BY time DESC
`

type GetLatestTemperatureParams struct {
	AgentID pgtype.UUID     `json:"agent_id"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) GetLatestTemperature(ctx context.Context, arg GetLatestTemperatureParams) ([]MetricsTemperature, error) {
	rows, err := q.db.Query(ctx, getLatestTemperature, arg.AgentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsTemperature{}
	for rows.Next() {
		var i MetricsTemperature
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Sensor,
			&i.Temperature,
			&i.MaxTemp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
