// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics_bucketed.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCPUBucketed = `-- name: GetCPUBucketed :many

SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    AVG(usage)::float8 AS usage,
    NULL::float8[] AS core_usages,
    AVG(load_1m)::float8 AS load_1m,
    AVG(load_5m)::float8 AS load_5m,
    AVG(load_15m)::float8 AS load_15m,
    AVG(iowait)::float8 AS iowait
FROM metrics_cpu
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2
ORDER BY 1 ASC
`

type GetCPUBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetCPUBucketedRow struct {
	Time       pgtype.Timestamptz `json:"time"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	Usage      float64            `json:"usage"`
	CoreUsages []float64          `json:"core_usages"`
	Load1m     float64            `json:"load_1m"`
	Load5m     float64            `json:"load_5m"`
	Load15m    float64            `json:"load_15m"`
	Iowait     float64            `json:"iowait"`
}

// Bucketed metric queries using TimescaleDB time_bucket.
// The interval parameter controls aggregation granularity.
// Handlers pick the bucket size based on the time range:
//
//	<= 1h: no bucketing
//	<= 6h: 1m
//	<= 24h: 5m
//	<= 7d: 15m
//	<= 30d: 1h
func (q *Queries) GetCPUBucketed(ctx context.Context, arg GetCPUBucketedParams) ([]GetCPUBucketedRow, error) {
	rows, err := q.db.Query(ctx, getCPUBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCPUBucketedRow{}
	for rows.Next() {
		var i GetCPUBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Usage,
			&i.CoreUsages,
			&i.Load1m,
			&i.Load5m,
			&i.Load15m,
			&i.Iowait,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContainerBucketed = `-- name: GetContainerBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    container_id,
    MAX(name)::text AS name,
    MAX(image)::text AS image,
    MAX(state)::text AS state,
    MAX(source)::text AS source,
    MAX(kind)::text AS kind,
    AVG(cpu_percent)::float8 AS cpu_percent,
    AVG(cpu_cores)::float8 AS cpu_cores,
    AVG(memory_bytes)::float8 AS memory_bytes,
    AVG(memory_limit)::float8 AS memory_limit,
    AVG(net_rx_bytes)::float8 AS net_rx_bytes,
    AVG(net_tx_bytes)::float8 AS net_tx_bytes
FROM metrics_container
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2, 3
ORDER BY 1 ASC
`

type GetContainerBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetContainerBucketedRow struct {
	Time        pgtype.Timestamptz `json:"time"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	ContainerID pgtype.Text        `json:"container_id"`
	Name        string             `json:"name"`
	Image       string             `json:"image"`
	State       string             `json:"state"`
	Source      string             `json:"source"`
	Kind        string             `json:"kind"`
	CpuPercent  float64            `json:"cpu_percent"`
	CpuCores    float64            `json:"cpu_cores"`
	MemoryBytes float64            `json:"memory_bytes"`
	MemoryLimit float64            `json:"memory_limit"`
	NetRxBytes  float64            `json:"net_rx_bytes"`
	NetTxBytes  float64            `json:"net_tx_bytes"`
}

func (q *Queries) GetContainerBucketed(ctx context.Context, arg GetContainerBucketedParams) ([]GetContainerBucketedRow, error) {
	rows, err := q.db.Query(ctx, getContainerBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContainerBucketedRow{}
	for rows.Next() {
		var i GetContainerBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.ContainerID,
			&i.Name,
			&i.Image,
			&i.State,
			&i.Source,
			&i.Kind,
			&i.CpuPercent,
			&i.CpuCores,
			&i.MemoryBytes,
			&i.MemoryLimit,
			&i.NetRxBytes,
			&i.NetTxBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiskBucketed = `-- name: GetDiskBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    device,
    mountpoint,
    filesystem,
    disk_type,
    AVG(total_bytes)::float8 AS total_bytes,
    AVG(used_bytes)::float8 AS used_bytes,
    AVG(free_bytes)::float8 AS free_bytes,
    AVG(used_percent)::float8 AS used_percent,
    AVG(inodes_total)::float8 AS inodes_total,
    AVG(inodes_used)::float8 AS inodes_used,
    AVG(inodes_percent)::float8 AS inodes_percent
FROM metrics_disk
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2, 3, 4, 5, 6
ORDER BY 1 ASC
`

type GetDiskBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetDiskBucketedRow struct {
	Time          pgtype.Timestamptz `json:"time"`
	AgentID       pgtype.UUID        `json:"agent_id"`
	Device        pgtype.Text        `json:"device"`
	Mountpoint    pgtype.Text        `json:"mountpoint"`
	Filesystem    pgtype.Text        `json:"filesystem"`
	DiskType      pgtype.Text        `json:"disk_type"`
	TotalBytes    float64            `json:"total_bytes"`
	UsedBytes     float64            `json:"used_bytes"`
	FreeBytes     float64            `json:"free_bytes"`
	UsedPercent   float64            `json:"used_percent"`
	InodesTotal   float64            `json:"inodes_total"`
	InodesUsed    float64            `json:"inodes_used"`
	InodesPercent float64            `json:"inodes_percent"`
}

func (q *Queries) GetDiskBucketed(ctx context.Context, arg GetDiskBucketedParams) ([]GetDiskBucketedRow, error) {
	rows, err := q.db.Query(ctx, getDiskBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiskBucketedRow{}
	for rows.Next() {
		var i GetDiskBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Device,
			&i.Mountpoint,
			&i.Filesystem,
			&i.DiskType,
			&i.TotalBytes,
			&i.UsedBytes,
			&i.FreeBytes,
			&i.UsedPercent,
			&i.InodesTotal,
			&i.InodesUsed,
			&i.InodesPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiskIOBucketed = `-- name: GetDiskIOBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    device,
    AVG(read_bytes)::float8 AS read_bytes,
    AVG(write_bytes)::float8 AS write_bytes,
    AVG(read_ops)::float8 AS read_ops,
    AVG(write_ops)::float8 AS write_ops,
    AVG(read_latency)::float8 AS read_latency,
    AVG(write_latency)::float8 AS write_latency,
    AVG(io_in_progress)::float8 AS io_in_progress
FROM metrics_disk_io
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2, 3
ORDER BY 1 ASC
`

type GetDiskIOBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetDiskIOBucketedRow struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Device       pgtype.Text        `json:"device"`
	ReadBytes    float64            `json:"read_bytes"`
	WriteBytes   float64            `json:"write_bytes"`
	ReadOps      float64            `json:"read_ops"`
	WriteOps     float64            `json:"write_ops"`
	ReadLatency  float64            `json:"read_latency"`
	WriteLatency float64            `json:"write_latency"`
	IoInProgress float64            `json:"io_in_progress"`
}

func (q *Queries) GetDiskIOBucketed(ctx context.Context, arg GetDiskIOBucketedParams) ([]GetDiskIOBucketedRow, error) {
	rows, err := q.db.Query(ctx, getDiskIOBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiskIOBucketedRow{}
	for rows.Next() {
		var i GetDiskIOBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Device,
			&i.ReadBytes,
			&i.WriteBytes,
			&i.ReadOps,
			&i.WriteOps,
			&i.ReadLatency,
			&i.WriteLatency,
			&i.IoInProgress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemoryBucketed = `-- name: GetMemoryBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    AVG(ram_total)::float8 AS ram_total,
    AVG(ram_used)::float8 AS ram_used,
    AVG(ram_available)::float8 AS ram_available,
    AVG(ram_percent)::float8 AS ram_percent,
    AVG(swap_total)::float8 AS swap_total,
    AVG(swap_used)::float8 AS swap_used,
    AVG(swap_percent)::float8 AS swap_percent
FROM metrics_memory
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2
ORDER BY 1 ASC
`

type GetMemoryBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetMemoryBucketedRow struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	RamTotal     float64            `json:"ram_total"`
	RamUsed      float64            `json:"ram_used"`
	RamAvailable float64            `json:"ram_available"`
	RamPercent   float64            `json:"ram_percent"`
	SwapTotal    float64            `json:"swap_total"`
	SwapUsed     float64            `json:"swap_used"`
	SwapPercent  float64            `json:"swap_percent"`
}

func (q *Queries) GetMemoryBucketed(ctx context.Context, arg GetMemoryBucketedParams) ([]GetMemoryBucketedRow, error) {
	rows, err := q.db.Query(ctx, getMemoryBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMemoryBucketedRow{}
	for rows.Next() {
		var i GetMemoryBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.RamTotal,
			&i.RamUsed,
			&i.RamAvailable,
			&i.RamPercent,
			&i.SwapTotal,
			&i.SwapUsed,
			&i.SwapPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNetworkBucketed = `-- name: GetNetworkBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    interface,
    MAX(mac)::text AS mac,
    MAX(mtu)::bigint AS mtu,
    MAX(speed)::bigint AS speed,
    AVG(rx_bytes)::float8 AS rx_bytes,
    AVG(rx_packets)::float8 AS rx_packets,
    AVG(rx_errors)::float8 AS rx_errors,
    AVG(rx_drops)::float8 AS rx_drops,
    AVG(tx_bytes)::float8 AS tx_bytes,
    AVG(tx_packets)::float8 AS tx_packets,
    AVG(tx_errors)::float8 AS tx_errors,
    AVG(tx_drops)::float8 AS tx_drops
FROM metrics_network
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2, 3
ORDER BY 1 ASC
`

type GetNetworkBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetNetworkBucketedRow struct {
	Time      pgtype.Timestamptz `json:"time"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Interface pgtype.Text        `json:"interface"`
	Mac       string             `json:"mac"`
	Mtu       int64              `json:"mtu"`
	Speed     int64              `json:"speed"`
	RxBytes   float64            `json:"rx_bytes"`
	RxPackets float64            `json:"rx_packets"`
	RxErrors  float64            `json:"rx_errors"`
	RxDrops   float64            `json:"rx_drops"`
	TxBytes   float64            `json:"tx_bytes"`
	TxPackets float64            `json:"tx_packets"`
	TxErrors  float64            `json:"tx_errors"`
	TxDrops   float64            `json:"tx_drops"`
}

func (q *Queries) GetNetworkBucketed(ctx context.Context, arg GetNetworkBucketedParams) ([]GetNetworkBucketedRow, error) {
	rows, err := q.db.Query(ctx, getNetworkBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNetworkBucketedRow{}
	for rows.Next() {
		var i GetNetworkBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Interface,
			&i.Mac,
			&i.Mtu,
			&i.Speed,
			&i.RxBytes,
			&i.RxPackets,
			&i.RxErrors,
			&i.RxDrops,
			&i.TxBytes,
			&i.TxPackets,
			&i.TxErrors,
			&i.TxDrops,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPiBucketed = `-- name: GetPiBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    MAX(metric_type)::text AS metric_type,
    AVG(arm_freq_hz)::float8 AS arm_freq_hz,
    AVG(core_freq_hz)::float8 AS core_freq_hz,
    AVG(gpu_freq_hz)::float8 AS gpu_freq_hz,
    AVG(core_volts)::float8 AS core_volts,
    AVG(sdram_c_volts)::float8 AS sdram_c_volts,
    AVG(sdram_i_volts)::float8 AS sdram_i_volts,
    AVG(sdram_p_volts)::float8 AS sdram_p_volts,
    AVG(soft_temp_limit)::float8 AS soft_temp_limit,
    BOOL_OR(throttled) AS throttled,
    BOOL_OR(under_voltage) AS under_voltage,
    BOOL_OR(freq_capped) AS freq_capped,
    BOOL_OR(undervoltage_occurred) AS undervoltage_occurred,
    BOOL_OR(freq_cap_occurred) AS freq_cap_occurred,
    BOOL_OR(throttled_occurred) AS throttled_occurred,
    BOOL_OR(soft_temp_limit_occurred) AS soft_temp_limit_occurred,
    AVG(gpu_mem_total)::float8 AS gpu_mem_total,
    AVG(gpu_mem_used)::float8 AS gpu_mem_used,
    AVG(gpu_temp)::float8 AS gpu_temp
FROM metrics_pi
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2
ORDER BY 1 ASC
`

type GetPiBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetPiBucketedRow struct {
	Time                  pgtype.Timestamptz `json:"time"`
	AgentID               pgtype.UUID        `json:"agent_id"`
	MetricType            string             `json:"metric_type"`
	ArmFreqHz             float64            `json:"arm_freq_hz"`
	CoreFreqHz            float64            `json:"core_freq_hz"`
	GpuFreqHz             float64            `json:"gpu_freq_hz"`
	CoreVolts             float64            `json:"core_volts"`
	SdramCVolts           float64            `json:"sdram_c_volts"`
	SdramIVolts           float64            `json:"sdram_i_volts"`
	SdramPVolts           float64            `json:"sdram_p_volts"`
	SoftTempLimit         float64            `json:"soft_temp_limit"`
	Throttled             bool               `json:"throttled"`
	UnderVoltage          bool               `json:"under_voltage"`
	FreqCapped            bool               `json:"freq_capped"`
	UndervoltageOccurred  bool               `json:"undervoltage_occurred"`
	FreqCapOccurred       bool               `json:"freq_cap_occurred"`
	ThrottledOccurred     bool               `json:"throttled_occurred"`
	SoftTempLimitOccurred bool               `json:"soft_temp_limit_occurred"`
	GpuMemTotal           float64            `json:"gpu_mem_total"`
	GpuMemUsed            float64            `json:"gpu_mem_used"`
	GpuTemp               float64            `json:"gpu_temp"`
}

func (q *Queries) GetPiBucketed(ctx context.Context, arg GetPiBucketedParams) ([]GetPiBucketedRow, error) {
	rows, err := q.db.Query(ctx, getPiBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPiBucketedRow{}
	for rows.Next() {
		var i GetPiBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.MetricType,
			&i.ArmFreqHz,
			&i.CoreFreqHz,
			&i.GpuFreqHz,
			&i.CoreVolts,
			&i.SdramCVolts,
			&i.SdramIVolts,
			&i.SdramPVolts,
			&i.SoftTempLimit,
			&i.Throttled,
			&i.UnderVoltage,
			&i.FreqCapped,
			&i.UndervoltageOccurred,
			&i.FreqCapOccurred,
			&i.ThrottledOccurred,
			&i.SoftTempLimitOccurred,
			&i.GpuMemTotal,
			&i.GpuMemUsed,
			&i.GpuTemp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemBucketed = `-- name: GetSystemBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    AVG(uptime)::float8 AS uptime,
    AVG(process_count)::float8 AS process_count,
    AVG(user_count)::float8 AS user_count,
    MAX(boot_time)::timestamptz AS boot_time
FROM metrics_system
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2
ORDER BY 1 ASC
`

type GetSystemBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetSystemBucketedRow struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Uptime       float64            `json:"uptime"`
	ProcessCount float64            `json:"process_count"`
	UserCount    float64            `json:"user_count"`
	BootTime     pgtype.Timestamptz `json:"boot_time"`
}

func (q *Queries) GetSystemBucketed(ctx context.Context, arg GetSystemBucketedParams) ([]GetSystemBucketedRow, error) {
	rows, err := q.db.Query(ctx, getSystemBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSystemBucketedRow{}
	for rows.Next() {
		var i GetSystemBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Uptime,
			&i.ProcessCount,
			&i.UserCount,
			&i.BootTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemperatureBucketed = `-- name: GetTemperatureBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    sensor,
    AVG(temperature)::float8 AS temperature,
    COALESCE(MAX(max_temp), 0)::float8 AS max_temp
FROM metrics_temperature
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2, 3
ORDER BY 1 ASC
`

type GetTemperatureBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetTemperatureBucketedRow struct {
	Time        pgtype.Timestamptz `json:"time"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Sensor      pgtype.Text        `json:"sensor"`
	Temperature float64            `json:"temperature"`
	MaxTemp     float64            `json:"max_temp"`
}

func (q *Queries) GetTemperatureBucketed(ctx context.Context, arg GetTemperatureBucketedParams) ([]GetTemperatureBucketedRow, error) {
	rows, err := q.db.Query(ctx, getTemperatureBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTemperatureBucketedRow{}
	for rows.Next() {
		var i GetTemperatureBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Sensor,
			&i.Temperature,
			&i.MaxTemp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWifiBucketed = `-- name: GetWifiBucketed :many
SELECT
    time_bucket(($1)::text::interval, time)::timestamptz AS time,
    agent_id,
    interface,
    MAX(ssid)::text AS ssid,
    MAX(bssid)::text AS bssid,
    AVG(frequency_mhz)::float8 AS frequency_mhz,
    AVG(signal_dbm)::float8 AS signal_dbm,
    AVG(noise_dbm)::float8 AS noise_dbm,
    AVG(bitrate_mbps)::float8 AS bitrate_mbps,
    AVG(link_quality)::float8 AS link_quality
FROM metrics_wifi
WHERE agent_id = $2 AND time >= $3 AND time <= $4
GROUP BY 1, 2, 3
ORDER BY 1 ASC
`

type GetWifiBucketedParams struct {
	BucketInterval string             `json:"bucket_interval"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetWifiBucketedRow struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Interface    pgtype.Text        `json:"interface"`
	Ssid         string             `json:"ssid"`
	Bssid        string             `json:"bssid"`
	FrequencyMhz float64            `json:"frequency_mhz"`
	SignalDbm    float64            `json:"signal_dbm"`
	NoiseDbm     float64            `json:"noise_dbm"`
	BitrateMbps  float64            `json:"bitrate_mbps"`
	LinkQuality  float64            `json:"link_quality"`
}

func (q *Queries) GetWifiBucketed(ctx context.Context, arg GetWifiBucketedParams) ([]GetWifiBucketedRow, error) {
	rows, err := q.db.Query(ctx, getWifiBucketed,
		arg.BucketInterval,
		arg.AgentID,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWifiBucketedRow{}
	for rows.Next() {
		var i GetWifiBucketedRow
		if err := rows.Scan(
			&i.Time,
			&i.AgentID,
			&i.Interface,
			&i.Ssid,
			&i.Bssid,
			&i.FrequencyMhz,
			&i.SignalDbm,
			&i.NoiseDbm,
			&i.BitrateMbps,
			&i.LinkQuality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
