// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics_insert.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCPU = `-- name: InsertCPU :exec
INSERT INTO metrics_cpu (time, agent_id, usage, core_usages, load_1m, load_5m, load_15m, iowait)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertCPUParams struct {
	Time       pgtype.Timestamptz `json:"time"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	Usage      pgtype.Float8      `json:"usage"`
	CoreUsages []float64          `json:"core_usages"`
	Load1m     pgtype.Float8      `json:"load_1m"`
	Load5m     pgtype.Float8      `json:"load_5m"`
	Load15m    pgtype.Float8      `json:"load_15m"`
	Iowait     pgtype.Float8      `json:"iowait"`
}

func (q *Queries) InsertCPU(ctx context.Context, arg InsertCPUParams) error {
	_, err := q.db.Exec(ctx, insertCPU,
		arg.Time,
		arg.AgentID,
		arg.Usage,
		arg.CoreUsages,
		arg.Load1m,
		arg.Load5m,
		arg.Load15m,
		arg.Iowait,
	)
	return err
}

const insertContainer = `-- name: InsertContainer :exec
INSERT INTO metrics_container (time, agent_id, container_id, name, image, state, source, kind, cpu_percent, cpu_cores, memory_bytes, memory_limit, net_rx_bytes, net_tx_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertContainerParams struct {
	Time        pgtype.Timestamptz `json:"time"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	ContainerID pgtype.Text        `json:"container_id"`
	Name        pgtype.Text        `json:"name"`
	Image       pgtype.Text        `json:"image"`
	State       pgtype.Text        `json:"state"`
	Source      pgtype.Text        `json:"source"`
	Kind        pgtype.Text        `json:"kind"`
	CpuPercent  pgtype.Float8      `json:"cpu_percent"`
	CpuCores    pgtype.Int4        `json:"cpu_cores"`
	MemoryBytes pgtype.Int8        `json:"memory_bytes"`
	MemoryLimit pgtype.Int8        `json:"memory_limit"`
	NetRxBytes  pgtype.Int8        `json:"net_rx_bytes"`
	NetTxBytes  pgtype.Int8        `json:"net_tx_bytes"`
}

func (q *Queries) InsertContainer(ctx context.Context, arg InsertContainerParams) error {
	_, err := q.db.Exec(ctx, insertContainer,
		arg.Time,
		arg.AgentID,
		arg.ContainerID,
		arg.Name,
		arg.Image,
		arg.State,
		arg.Source,
		arg.Kind,
		arg.CpuPercent,
		arg.CpuCores,
		arg.MemoryBytes,
		arg.MemoryLimit,
		arg.NetRxBytes,
		arg.NetTxBytes,
	)
	return err
}

const insertDisk = `-- name: InsertDisk :exec
INSERT INTO metrics_disk (time, agent_id, device, mountpoint, filesystem, disk_type, total_bytes, used_bytes, free_bytes, used_percent, inodes_total, inodes_used, inodes_percent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertDiskParams struct {
	Time          pgtype.Timestamptz `json:"time"`
	AgentID       pgtype.UUID        `json:"agent_id"`
	Device        pgtype.Text        `json:"device"`
	Mountpoint    pgtype.Text        `json:"mountpoint"`
	Filesystem    pgtype.Text        `json:"filesystem"`
	DiskType      pgtype.Text        `json:"disk_type"`
	TotalBytes    pgtype.Int8        `json:"total_bytes"`
	UsedBytes     pgtype.Int8        `json:"used_bytes"`
	FreeBytes     pgtype.Int8        `json:"free_bytes"`
	UsedPercent   pgtype.Float8      `json:"used_percent"`
	InodesTotal   pgtype.Int8        `json:"inodes_total"`
	InodesUsed    pgtype.Int8        `json:"inodes_used"`
	InodesPercent pgtype.Float8      `json:"inodes_percent"`
}

func (q *Queries) InsertDisk(ctx context.Context, arg InsertDiskParams) error {
	_, err := q.db.Exec(ctx, insertDisk,
		arg.Time,
		arg.AgentID,
		arg.Device,
		arg.Mountpoint,
		arg.Filesystem,
		arg.DiskType,
		arg.TotalBytes,
		arg.UsedBytes,
		arg.FreeBytes,
		arg.UsedPercent,
		arg.InodesTotal,
		arg.InodesUsed,
		arg.InodesPercent,
	)
	return err
}

const insertDiskIO = `-- name: InsertDiskIO :exec
INSERT INTO metrics_disk_io (time, agent_id, device, read_bytes, write_bytes, read_ops, write_ops, read_latency, write_latency, io_in_progress)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertDiskIOParams struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Device       pgtype.Text        `json:"device"`
	ReadBytes    pgtype.Int8        `json:"read_bytes"`
	WriteBytes   pgtype.Int8        `json:"write_bytes"`
	ReadOps      pgtype.Int8        `json:"read_ops"`
	WriteOps     pgtype.Int8        `json:"write_ops"`
	ReadLatency  pgtype.Int8        `json:"read_latency"`
	WriteLatency pgtype.Int8        `json:"write_latency"`
	IoInProgress pgtype.Int8        `json:"io_in_progress"`
}

func (q *Queries) InsertDiskIO(ctx context.Context, arg InsertDiskIOParams) error {
	_, err := q.db.Exec(ctx, insertDiskIO,
		arg.Time,
		arg.AgentID,
		arg.Device,
		arg.ReadBytes,
		arg.WriteBytes,
		arg.ReadOps,
		arg.WriteOps,
		arg.ReadLatency,
		arg.WriteLatency,
		arg.IoInProgress,
	)
	return err
}

const insertMemory = `-- name: InsertMemory :exec
INSERT INTO metrics_memory (time, agent_id, ram_total, ram_used, ram_available, ram_percent, swap_total, swap_used, swap_percent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertMemoryParams struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	RamTotal     pgtype.Int8        `json:"ram_total"`
	RamUsed      pgtype.Int8        `json:"ram_used"`
	RamAvailable pgtype.Int8        `json:"ram_available"`
	RamPercent   pgtype.Float8      `json:"ram_percent"`
	SwapTotal    pgtype.Int8        `json:"swap_total"`
	SwapUsed     pgtype.Int8        `json:"swap_used"`
	SwapPercent  pgtype.Float8      `json:"swap_percent"`
}

func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) error {
	_, err := q.db.Exec(ctx, insertMemory,
		arg.Time,
		arg.AgentID,
		arg.RamTotal,
		arg.RamUsed,
		arg.RamAvailable,
		arg.RamPercent,
		arg.SwapTotal,
		arg.SwapUsed,
		arg.SwapPercent,
	)
	return err
}

const insertNetwork = `-- name: InsertNetwork :exec
INSERT INTO metrics_network (time, agent_id, interface, mac, mtu, speed, rx_bytes, rx_packets, rx_errors, rx_drops, tx_bytes, tx_packets, tx_errors, tx_drops)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertNetworkParams struct {
	Time      pgtype.Timestamptz `json:"time"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Interface pgtype.Text        `json:"interface"`
	Mac       pgtype.Text        `json:"mac"`
	Mtu       pgtype.Int4        `json:"mtu"`
	Speed     pgtype.Int8        `json:"speed"`
	RxBytes   pgtype.Int8        `json:"rx_bytes"`
	RxPackets pgtype.Int8        `json:"rx_packets"`
	RxErrors  pgtype.Int8        `json:"rx_errors"`
	RxDrops   pgtype.Int8        `json:"rx_drops"`
	TxBytes   pgtype.Int8        `json:"tx_bytes"`
	TxPackets pgtype.Int8        `json:"tx_packets"`
	TxErrors  pgtype.Int8        `json:"tx_errors"`
	TxDrops   pgtype.Int8        `json:"tx_drops"`
}

func (q *Queries) InsertNetwork(ctx context.Context, arg InsertNetworkParams) error {
	_, err := q.db.Exec(ctx, insertNetwork,
		arg.Time,
		arg.AgentID,
		arg.Interface,
		arg.Mac,
		arg.Mtu,
		arg.Speed,
		arg.RxBytes,
		arg.RxPackets,
		arg.RxErrors,
		arg.RxDrops,
		arg.TxBytes,
		arg.TxPackets,
		arg.TxErrors,
		arg.TxDrops,
	)
	return err
}

const insertPi = `-- name: InsertPi :exec
INSERT INTO metrics_pi (time, agent_id, metric_type, arm_freq_hz, core_freq_hz, gpu_freq_hz, core_volts, sdram_c_volts, sdram_i_volts, sdram_p_volts, soft_temp_limit, throttled, under_voltage, freq_capped, undervoltage_occurred, freq_cap_occurred, throttled_occurred, soft_temp_limit_occurred, gpu_mem_total, gpu_mem_used, gpu_temp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
`

type InsertPiParams struct {
	Time                  pgtype.Timestamptz `json:"time"`
	AgentID               pgtype.UUID        `json:"agent_id"`
	MetricType            string             `json:"metric_type"`
	ArmFreqHz             pgtype.Int8        `json:"arm_freq_hz"`
	CoreFreqHz            pgtype.Int8        `json:"core_freq_hz"`
	GpuFreqHz             pgtype.Int8        `json:"gpu_freq_hz"`
	CoreVolts             pgtype.Float8      `json:"core_volts"`
	SdramCVolts           pgtype.Float8      `json:"sdram_c_volts"`
	SdramIVolts           pgtype.Float8      `json:"sdram_i_volts"`
	SdramPVolts           pgtype.Float8      `json:"sdram_p_volts"`
	SoftTempLimit         pgtype.Bool        `json:"soft_temp_limit"`
	Throttled             pgtype.Bool        `json:"throttled"`
	UnderVoltage          pgtype.Bool        `json:"under_voltage"`
	FreqCapped            pgtype.Bool        `json:"freq_capped"`
	UndervoltageOccurred  pgtype.Bool        `json:"undervoltage_occurred"`
	FreqCapOccurred       pgtype.Bool        `json:"freq_cap_occurred"`
	ThrottledOccurred     pgtype.Bool        `json:"throttled_occurred"`
	SoftTempLimitOccurred pgtype.Bool        `json:"soft_temp_limit_occurred"`
	GpuMemTotal           pgtype.Int8        `json:"gpu_mem_total"`
	GpuMemUsed            pgtype.Int8        `json:"gpu_mem_used"`
	GpuTemp               pgtype.Float8      `json:"gpu_temp"`
}

func (q *Queries) InsertPi(ctx context.Context, arg InsertPiParams) error {
	_, err := q.db.Exec(ctx, insertPi,
		arg.Time,
		arg.AgentID,
		arg.MetricType,
		arg.ArmFreqHz,
		arg.CoreFreqHz,
		arg.GpuFreqHz,
		arg.CoreVolts,
		arg.SdramCVolts,
		arg.SdramIVolts,
		arg.SdramPVolts,
		arg.SoftTempLimit,
		arg.Throttled,
		arg.UnderVoltage,
		arg.FreqCapped,
		arg.UndervoltageOccurred,
		arg.FreqCapOccurred,
		arg.ThrottledOccurred,
		arg.SoftTempLimitOccurred,
		arg.GpuMemTotal,
		arg.GpuMemUsed,
		arg.GpuTemp,
	)
	return err
}

const insertSystem = `-- name: InsertSystem :exec
INSERT INTO metrics_system (time, agent_id, uptime, process_count, user_count, boot_time)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSystemParams struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Uptime       pgtype.Int8        `json:"uptime"`
	ProcessCount pgtype.Int4        `json:"process_count"`
	UserCount    pgtype.Int4        `json:"user_count"`
	BootTime     pgtype.Int8        `json:"boot_time"`
}

func (q *Queries) InsertSystem(ctx context.Context, arg InsertSystemParams) error {
	_, err := q.db.Exec(ctx, insertSystem,
		arg.Time,
		arg.AgentID,
		arg.Uptime,
		arg.ProcessCount,
		arg.UserCount,
		arg.BootTime,
	)
	return err
}

const insertTemperature = `-- name: InsertTemperature :exec
INSERT INTO metrics_temperature (time, agent_id, sensor, temperature, max_temp)
VALUES ($1, $2, $3, $4, $5)
`

type InsertTemperatureParams struct {
	Time        pgtype.Timestamptz `json:"time"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Sensor      pgtype.Text        `json:"sensor"`
	Temperature pgtype.Float8      `json:"temperature"`
	MaxTemp     pgtype.Float8      `json:"max_temp"`
}

func (q *Queries) InsertTemperature(ctx context.Context, arg InsertTemperatureParams) error {
	_, err := q.db.Exec(ctx, insertTemperature,
		arg.Time,
		arg.AgentID,
		arg.Sensor,
		arg.Temperature,
		arg.MaxTemp,
	)
	return err
}

const insertWifi = `-- name: InsertWifi :exec
INSERT INTO metrics_wifi (time, agent_id, interface, ssid, bssid, frequency_mhz, signal_dbm, noise_dbm, bitrate_mbps)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertWifiParams struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Interface    pgtype.Text        `json:"interface"`
	Ssid         pgtype.Text        `json:"ssid"`
	Bssid        pgtype.Text        `json:"bssid"`
	FrequencyMhz pgtype.Int4        `json:"frequency_mhz"`
	SignalDbm    pgtype.Int4        `json:"signal_dbm"`
	NoiseDbm     pgtype.Int4        `json:"noise_dbm"`
	BitrateMbps  pgtype.Float8      `json:"bitrate_mbps"`
}

func (q *Queries) InsertWifi(ctx context.Context, arg InsertWifiParams) error {
	_, err := q.db.Exec(ctx, insertWifi,
		arg.Time,
		arg.AgentID,
		arg.Interface,
		arg.Ssid,
		arg.Bssid,
		arg.FrequencyMhz,
		arg.SignalDbm,
		arg.NoiseDbm,
		arg.BitrateMbps,
	)
	return err
}
