// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           pgtype.UUID        `json:"id"`
	SecretHash   string             `json:"secret_hash"`
	Hostname     string             `json:"hostname"`
	Os           pgtype.Text        `json:"os"`
	Platform     pgtype.Text        `json:"platform"`
	Arch         pgtype.Text        `json:"arch"`
	CpuModel     pgtype.Text        `json:"cpu_model"`
	CpuCores     pgtype.Int4        `json:"cpu_cores"`
	RamTotal     pgtype.Int8        `json:"ram_total"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
}

type CurrentApplication struct {
	AgentID   pgtype.UUID        `json:"agent_id"`
	Name      string             `json:"name"`
	Version   pgtype.Text        `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CurrentMetric struct {
	AgentID        pgtype.UUID        `json:"agent_id"`
	CpuUsage       pgtype.Float8      `json:"cpu_usage"`
	LoadNormalized pgtype.Float8      `json:"load_normalized"`
	RamPercent     pgtype.Float8      `json:"ram_percent"`
	SwapPercent    pgtype.Float8      `json:"swap_percent"`
	DiskMaxPercent pgtype.Float8      `json:"disk_max_percent"`
	NetRxBytes     pgtype.Int8        `json:"net_rx_bytes"`
	NetTxBytes     pgtype.Int8        `json:"net_tx_bytes"`
	MaxTemp        pgtype.Float8      `json:"max_temp"`
	Uptime         pgtype.Int8        `json:"uptime"`
	ProcessCount   pgtype.Int4        `json:"process_count"`
	RebootRequired bool               `json:"reboot_required"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CurrentProcess struct {
	AgentID    pgtype.UUID        `json:"agent_id"`
	Pid        int32              `json:"pid"`
	Name       pgtype.Text        `json:"name"`
	CpuPercent pgtype.Float8      `json:"cpu_percent"`
	MemPercent pgtype.Float8      `json:"mem_percent"`
	MemRss     pgtype.Int8        `json:"mem_rss"`
	Status     pgtype.Text        `json:"status"`
	Threads    pgtype.Int4        `json:"threads"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CurrentService struct {
	AgentID   pgtype.UUID        `json:"agent_id"`
	Name      string             `json:"name"`
	Status    pgtype.Text        `json:"status"`
	SubStatus pgtype.Text        `json:"sub_status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CurrentUpdate struct {
	AgentID        pgtype.UUID        `json:"agent_id"`
	PendingCount   int32              `json:"pending_count"`
	SecurityCount  int32              `json:"security_count"`
	RebootRequired bool               `json:"reboot_required"`
	PackageManager pgtype.Text        `json:"package_manager"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MetricsContainer struct {
	Time        pgtype.Timestamptz `json:"time"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	ContainerID pgtype.Text        `json:"container_id"`
	Name        pgtype.Text        `json:"name"`
	Image       pgtype.Text        `json:"image"`
	State       pgtype.Text        `json:"state"`
	Source      pgtype.Text        `json:"source"`
	Kind        pgtype.Text        `json:"kind"`
	CpuPercent  pgtype.Float8      `json:"cpu_percent"`
	CpuCores    pgtype.Int4        `json:"cpu_cores"`
	MemoryBytes pgtype.Int8        `json:"memory_bytes"`
	MemoryLimit pgtype.Int8        `json:"memory_limit"`
	NetRxBytes  pgtype.Int8        `json:"net_rx_bytes"`
	NetTxBytes  pgtype.Int8        `json:"net_tx_bytes"`
}

type MetricsCpu struct {
	Time       pgtype.Timestamptz `json:"time"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	Usage      pgtype.Float8      `json:"usage"`
	CoreUsages []float64          `json:"core_usages"`
	Load1m     pgtype.Float8      `json:"load_1m"`
	Load5m     pgtype.Float8      `json:"load_5m"`
	Load15m    pgtype.Float8      `json:"load_15m"`
	Iowait     pgtype.Float8      `json:"iowait"`
}

type MetricsDisk struct {
	Time          pgtype.Timestamptz `json:"time"`
	AgentID       pgtype.UUID        `json:"agent_id"`
	Device        pgtype.Text        `json:"device"`
	Mountpoint    pgtype.Text        `json:"mountpoint"`
	Filesystem    pgtype.Text        `json:"filesystem"`
	DiskType      pgtype.Text        `json:"disk_type"`
	TotalBytes    pgtype.Int8        `json:"total_bytes"`
	UsedBytes     pgtype.Int8        `json:"used_bytes"`
	FreeBytes     pgtype.Int8        `json:"free_bytes"`
	UsedPercent   pgtype.Float8      `json:"used_percent"`
	InodesTotal   pgtype.Int8        `json:"inodes_total"`
	InodesUsed    pgtype.Int8        `json:"inodes_used"`
	InodesPercent pgtype.Float8      `json:"inodes_percent"`
}

type MetricsDiskIo struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Device       pgtype.Text        `json:"device"`
	ReadBytes    pgtype.Int8        `json:"read_bytes"`
	WriteBytes   pgtype.Int8        `json:"write_bytes"`
	ReadOps      pgtype.Int8        `json:"read_ops"`
	WriteOps     pgtype.Int8        `json:"write_ops"`
	ReadLatency  pgtype.Int8        `json:"read_latency"`
	WriteLatency pgtype.Int8        `json:"write_latency"`
	IoInProgress pgtype.Int8        `json:"io_in_progress"`
}

type MetricsMemory struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	RamTotal     pgtype.Int8        `json:"ram_total"`
	RamUsed      pgtype.Int8        `json:"ram_used"`
	RamAvailable pgtype.Int8        `json:"ram_available"`
	RamPercent   pgtype.Float8      `json:"ram_percent"`
	SwapTotal    pgtype.Int8        `json:"swap_total"`
	SwapUsed     pgtype.Int8        `json:"swap_used"`
	SwapPercent  pgtype.Float8      `json:"swap_percent"`
}

type MetricsNetwork struct {
	Time      pgtype.Timestamptz `json:"time"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Interface pgtype.Text        `json:"interface"`
	Mac       pgtype.Text        `json:"mac"`
	Mtu       pgtype.Int4        `json:"mtu"`
	Speed     pgtype.Int8        `json:"speed"`
	RxBytes   pgtype.Int8        `json:"rx_bytes"`
	RxPackets pgtype.Int8        `json:"rx_packets"`
	RxErrors  pgtype.Int8        `json:"rx_errors"`
	RxDrops   pgtype.Int8        `json:"rx_drops"`
	TxBytes   pgtype.Int8        `json:"tx_bytes"`
	TxPackets pgtype.Int8        `json:"tx_packets"`
	TxErrors  pgtype.Int8        `json:"tx_errors"`
	TxDrops   pgtype.Int8        `json:"tx_drops"`
}

type MetricsPi struct {
	Time                  pgtype.Timestamptz `json:"time"`
	AgentID               pgtype.UUID        `json:"agent_id"`
	MetricType            string             `json:"metric_type"`
	ArmFreqHz             pgtype.Int8        `json:"arm_freq_hz"`
	CoreFreqHz            pgtype.Int8        `json:"core_freq_hz"`
	GpuFreqHz             pgtype.Int8        `json:"gpu_freq_hz"`
	CoreVolts             pgtype.Float8      `json:"core_volts"`
	SdramCVolts           pgtype.Float8      `json:"sdram_c_volts"`
	SdramIVolts           pgtype.Float8      `json:"sdram_i_volts"`
	SdramPVolts           pgtype.Float8      `json:"sdram_p_volts"`
	Throttled             pgtype.Bool        `json:"throttled"`
	UnderVoltage          pgtype.Bool        `json:"under_voltage"`
	FreqCapped            pgtype.Bool        `json:"freq_capped"`
	GpuMemTotal           pgtype.Int8        `json:"gpu_mem_total"`
	GpuMemUsed            pgtype.Int8        `json:"gpu_mem_used"`
	GpuTemp               pgtype.Float8      `json:"gpu_temp"`
	SoftTempLimit         pgtype.Bool        `json:"soft_temp_limit"`
	UndervoltageOccurred  pgtype.Bool        `json:"undervoltage_occurred"`
	FreqCapOccurred       pgtype.Bool        `json:"freq_cap_occurred"`
	ThrottledOccurred     pgtype.Bool        `json:"throttled_occurred"`
	SoftTempLimitOccurred pgtype.Bool        `json:"soft_temp_limit_occurred"`
}

type MetricsSystem struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Uptime       pgtype.Int8        `json:"uptime"`
	ProcessCount pgtype.Int4        `json:"process_count"`
	UserCount    pgtype.Int4        `json:"user_count"`
	BootTime     pgtype.Int8        `json:"boot_time"`
}

type MetricsTemperature struct {
	Time        pgtype.Timestamptz `json:"time"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Sensor      pgtype.Text        `json:"sensor"`
	Temperature pgtype.Float8      `json:"temperature"`
	MaxTemp     pgtype.Float8      `json:"max_temp"`
}

type MetricsWifi struct {
	Time         pgtype.Timestamptz `json:"time"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Interface    pgtype.Text        `json:"interface"`
	Ssid         pgtype.Text        `json:"ssid"`
	Bssid        pgtype.Text        `json:"bssid"`
	FrequencyMhz pgtype.Int4        `json:"frequency_mhz"`
	SignalDbm    pgtype.Int4        `json:"signal_dbm"`
	NoiseDbm     pgtype.Int4        `json:"noise_dbm"`
	BitrateMbps  pgtype.Float8      `json:"bitrate_mbps"`
	LinkQuality  pgtype.Int4        `json:"link_quality"`
}

type RegistrationToken struct {
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	UsedBy    pgtype.UUID        `json:"used_by"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    pgtype.UUID        `json:"user_id"`
	IpAddress string             `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
