// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overview.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOverview = `-- name: GetOverview :many
SELECT  a.id, a.hostname, a.os, a.platform, a.arch, a.cpu_cores, a.last_seen,
        m.cpu_usage, m.load_normalized, m.ram_percent, m.swap_percent,
        m.disk_max_percent, m.net_rx_bytes, m.net_tx_bytes, m.max_temp,
        m.uptime, m.process_count, m.reboot_required, m.updated_at
FROM agents a
LEFT JOIN current_metrics m ON a.id = m.agent_id
ORDER BY a.hostname
`

type GetOverviewRow struct {
	ID             pgtype.UUID        `json:"id"`
	Hostname       string             `json:"hostname"`
	Os             pgtype.Text        `json:"os"`
	Platform       pgtype.Text        `json:"platform"`
	Arch           pgtype.Text        `json:"arch"`
	CpuCores       pgtype.Int4        `json:"cpu_cores"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
	CpuUsage       pgtype.Float8      `json:"cpu_usage"`
	LoadNormalized pgtype.Float8      `json:"load_normalized"`
	RamPercent     pgtype.Float8      `json:"ram_percent"`
	SwapPercent    pgtype.Float8      `json:"swap_percent"`
	DiskMaxPercent pgtype.Float8      `json:"disk_max_percent"`
	NetRxBytes     pgtype.Int8        `json:"net_rx_bytes"`
	NetTxBytes     pgtype.Int8        `json:"net_tx_bytes"`
	MaxTemp        pgtype.Float8      `json:"max_temp"`
	Uptime         pgtype.Int8        `json:"uptime"`
	ProcessCount   pgtype.Int4        `json:"process_count"`
	RebootRequired pgtype.Bool        `json:"reboot_required"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOverview(ctx context.Context) ([]GetOverviewRow, error) {
	rows, err := q.db.Query(ctx, getOverview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverviewRow{}
	for rows.Next() {
		var i GetOverviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Hostname,
			&i.Os,
			&i.Platform,
			&i.Arch,
			&i.CpuCores,
			&i.LastSeen,
			&i.CpuUsage,
			&i.LoadNormalized,
			&i.RamPercent,
			&i.SwapPercent,
			&i.DiskMaxPercent,
			&i.NetRxBytes,
			&i.NetTxBytes,
			&i.MaxTemp,
			&i.Uptime,
			&i.ProcessCount,
			&i.RebootRequired,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCurrentCPU = `-- name: UpsertCurrentCPU :exec
INSERT INTO current_metrics (agent_id, cpu_usage, load_normalized, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (agent_id) DO UPDATE
SET cpu_usage = EXCLUDED.cpu_usage,
    load_normalized = EXCLUDED.load_normalized,
    updated_at = NOW()
`

type UpsertCurrentCPUParams struct {
	AgentID        pgtype.UUID   `json:"agent_id"`
	CpuUsage       pgtype.Float8 `json:"cpu_usage"`
	LoadNormalized pgtype.Float8 `json:"load_normalized"`
}

func (q *Queries) UpsertCurrentCPU(ctx context.Context, arg UpsertCurrentCPUParams) error {
	_, err := q.db.Exec(ctx, upsertCurrentCPU, arg.AgentID, arg.CpuUsage, arg.LoadNormalized)
	return err
}

const upsertCurrentDiskMax = `-- name: UpsertCurrentDiskMax :exec
INSERT INTO current_metrics (agent_id, disk_max_percent, updated_at)
VALUES ($1, (
    SELECT COALESCE(MAX(used_percent), 0)
    FROM metrics_disk
    WHERE agent_id = $1 AND time > NOW() - INTERVAL '5 minutes'
), NOW())
ON CONFLICT (agent_id) DO UPDATE
SET disk_max_percent = EXCLUDED.disk_max_percent,
    updated_at = NOW()
`

func (q *Queries) UpsertCurrentDiskMax(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, upsertCurrentDiskMax, agentID)
	return err
}

const upsertCurrentMemory = `-- name: UpsertCurrentMemory :exec
INSERT INTO current_metrics (agent_id, ram_percent, swap_percent, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (agent_id) DO UPDATE
SET ram_percent = EXCLUDED.ram_percent,
    swap_percent = EXCLUDED.swap_percent,
    updated_at = NOW()
`

type UpsertCurrentMemoryParams struct {
	AgentID     pgtype.UUID   `json:"agent_id"`
	RamPercent  pgtype.Float8 `json:"ram_percent"`
	SwapPercent pgtype.Float8 `json:"swap_percent"`
}

func (q *Queries) UpsertCurrentMemory(ctx context.Context, arg UpsertCurrentMemoryParams) error {
	_, err := q.db.Exec(ctx, upsertCurrentMemory, arg.AgentID, arg.RamPercent, arg.SwapPercent)
	return err
}

const upsertCurrentNetwork = `-- name: UpsertCurrentNetwork :exec
INSERT INTO current_metrics (agent_id, net_rx_bytes, net_tx_bytes, updated_at)
VALUES ($1, (
    SELECT COALESCE(SUM(rx_bytes), 0)
    FROM metrics_network
    WHERE agent_id = $1 AND time > NOW() - INTERVAL '15 seconds'
), (
    SELECT COALESCE(SUM(tx_bytes), 0)
    FROM metrics_network
    WHERE agent_id = $1 AND time > NOW() - INTERVAL '15 seconds'
), NOW())
ON CONFLICT (agent_id) DO UPDATE
SET net_rx_bytes = EXCLUDED.net_rx_bytes,
    net_tx_bytes = EXCLUDED.net_tx_bytes,
    updated_at = NOW()
`

func (q *Queries) UpsertCurrentNetwork(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, upsertCurrentNetwork, agentID)
	return err
}

const upsertCurrentReboot = `-- name: UpsertCurrentReboot :exec
INSERT INTO current_metrics (agent_id, reboot_required, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (agent_id) DO UPDATE
SET reboot_required = EXCLUDED.reboot_required,
    updated_at = NOW()
`

type UpsertCurrentRebootParams struct {
	AgentID        pgtype.UUID `json:"agent_id"`
	RebootRequired bool        `json:"reboot_required"`
}

func (q *Queries) UpsertCurrentReboot(ctx context.Context, arg UpsertCurrentRebootParams) error {
	_, err := q.db.Exec(ctx, upsertCurrentReboot, arg.AgentID, arg.RebootRequired)
	return err
}

const upsertCurrentSystem = `-- name: UpsertCurrentSystem :exec
INSERT INTO current_metrics (agent_id, uptime, process_count, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (agent_id) DO UPDATE
SET uptime = EXCLUDED.uptime,
    process_count = EXCLUDED.process_count,
    updated_at = NOW()
`

type UpsertCurrentSystemParams struct {
	AgentID      pgtype.UUID `json:"agent_id"`
	Uptime       pgtype.Int8 `json:"uptime"`
	ProcessCount pgtype.Int4 `json:"process_count"`
}

func (q *Queries) UpsertCurrentSystem(ctx context.Context, arg UpsertCurrentSystemParams) error {
	_, err := q.db.Exec(ctx, upsertCurrentSystem, arg.AgentID, arg.Uptime, arg.ProcessCount)
	return err
}

const upsertCurrentTemperature = `-- name: UpsertCurrentTemperature :exec
INSERT INTO current_metrics (agent_id, max_temp, updated_at)
VALUES ($1, (
    SELECT COALESCE(MAX(temperature), 0)
    FROM metrics_temperature
    WHERE agent_id = $1 AND time > NOW() - INTERVAL '15 seconds'
), NOW())
ON CONFLICT (agent_id) DO UPDATE
SET max_temp = EXCLUDED.max_temp,
    updated_at = NOW()
`

func (q *Queries) UpsertCurrentTemperature(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, upsertCurrentTemperature, agentID)
	return err
}
