// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: smtp_config.sql

package database

import (
	"context"
)

const getSMTPConfig = `-- name: GetSMTPConfig :one
SELECT id, enabled, host, port, username, password_encrypted, from_address, tls_mode, updated_at
FROM smtp_config
WHERE id = TRUE
`

// Returns the single SMTP config row. Returns no rows if SMTP has never been
// configured; callers treat pgx.ErrNoRows as "not configured".
func (q *Queries) GetSMTPConfig(ctx context.Context) (SmtpConfig, error) {
	row := q.db.QueryRow(ctx, getSMTPConfig)
	var i SmtpConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.FromAddress,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSMTPConfig = `-- name: UpsertSMTPConfig :one
INSERT INTO smtp_config (
	id, enabled, host, port, username, password_encrypted, from_address, tls_mode, updated_at
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
ON CONFLICT (id) DO UPDATE
SET	enabled = EXCLUDED.enabled,
	host = EXCLUDED.host,
	port = EXCLUDED.port,
	username = EXCLUDED.username,
	password_encrypted = EXCLUDED.password_encrypted,
	from_address = EXCLUDED.from_address,
	tls_mode = EXCCLUDED.tls_mode,
	updated_at = NOW()
RETURNING id, enabled, host, port, username, password_encrypted, from_address, tls_mode, updated_at
`

type UpsertSMTPConfigParams struct {
	ID                bool   `json:"id"`
	Enabled           bool   `json:"enabled"`
	Host              string `json:"host"`
	Port              int32  `json:"port"`
	Username          string `json:"username"`
	PasswordEncrypted string `json:"password_encrypted"`
	FromAddress       string `json:"from_address"`
	TlsMode           string `json:"tls_mode"`
}

// Inserts or updates the single SMTP config row. The fixed boolean PK means the
// ON CONFLICT path always targets the one existing row.
func (q *Queries) UpsertSMTPConfig(ctx context.Context, arg UpsertSMTPConfigParams) (SmtpConfig, error) {
	row := q.db.QueryRow(ctx, upsertSMTPConfig,
		arg.ID,
		arg.Enabled,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEncrypted,
		arg.FromAddress,
		arg.TlsMode,
	)
	var i SmtpConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.FromAddress,
		&i.TlsMode,
		&i.UpdatedAt,
	)
	return i, err
}
