// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sparklines.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentCPU = `-- name: GetRecentCPU :many
SELECT agent_id, time, usage
FROM metrics_cpu
WHERE time >= NOW() - INTERVAL '5 minutes'
ORDER BY agent_id, time ASC
`

type GetRecentCPURow struct {
	AgentID pgtype.UUID        `json:"agent_id"`
	Time    pgtype.Timestamptz `json:"time"`
	Usage   pgtype.Float8      `json:"usage"`
}

// Returns last 5 minutes of CPU usage for all agents, ordered chronologically.
func (q *Queries) GetRecentCPU(ctx context.Context) ([]GetRecentCPURow, error) {
	rows, err := q.db.Query(ctx, getRecentCPU)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentCPURow{}
	for rows.Next() {
		var i GetRecentCPURow
		if err := rows.Scan(&i.AgentID, &i.Time, &i.Usage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentDiskMax = `-- name: GetRecentDiskMax :many
SELECT agent_id, time, CAST(MAX(used_percent) AS DOUBLE PRECISION) AS max_percent
FROM metrics_disk
WHERE time >= NOW() - INTERVAL '5 minutes'
GROUP BY agent_id, time
ORDER BY agent_id, time ASC
`

type GetRecentDiskMaxRow struct {
	AgentID    pgtype.UUID        `json:"agent_id"`
	Time       pgtype.Timestamptz `json:"time"`
	MaxPercent float64            `json:"max_percent"`
}

// Returns last 5 minutes of max disk usage per timestamp per agent.
func (q *Queries) GetRecentDiskMax(ctx context.Context) ([]GetRecentDiskMaxRow, error) {
	rows, err := q.db.Query(ctx, getRecentDiskMax)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentDiskMaxRow{}
	for rows.Next() {
		var i GetRecentDiskMaxRow
		if err := rows.Scan(&i.AgentID, &i.Time, &i.MaxPercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMemory = `-- name: GetRecentMemory :many
SELECT agent_id, time, ram_percent
FROM metrics_memory
WHERE time >= NOW() - INTERVAL '5 minutes'
ORDER BY agent_id, time ASC
`

type GetRecentMemoryRow struct {
	AgentID    pgtype.UUID        `json:"agent_id"`
	Time       pgtype.Timestamptz `json:"time"`
	RamPercent pgtype.Float8      `json:"ram_percent"`
}

// Returns last 5 minutes of RAM percent for all agents, ordered chronologically.
func (q *Queries) GetRecentMemory(ctx context.Context) ([]GetRecentMemoryRow, error) {
	rows, err := q.db.Query(ctx, getRecentMemory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentMemoryRow{}
	for rows.Next() {
		var i GetRecentMemoryRow
		if err := rows.Scan(&i.AgentID, &i.Time, &i.RamPercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
