// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sparklines.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFleetSparkCPU = `-- name: GetFleetSparkCPU :many
SELECT
    time_bucket(($1)::text::interval, c.time)::timestamptz AS bucket,
    c.agent_id,
    AVG(c.usage)::float8 AS usage
FROM metrics_cpu c
WHERE c.time >= $2 AND c.time <= $3
GROUP BY 1, 2
ORDER BY 2, 1 ASC
`

type GetFleetSparkCPUParams struct {
	BucketInterval string             `json:"bucket_interval"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetFleetSparkCPURow struct {
	Bucket  pgtype.Timestamptz `json:"bucket"`
	AgentID pgtype.UUID        `json:"agent_id"`
	Usage   float64            `json:"usage"`
}

func (q *Queries) GetFleetSparkCPU(ctx context.Context, arg GetFleetSparkCPUParams) ([]GetFleetSparkCPURow, error) {
	rows, err := q.db.Query(ctx, getFleetSparkCPU, arg.BucketInterval, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFleetSparkCPURow{}
	for rows.Next() {
		var i GetFleetSparkCPURow
		if err := rows.Scan(&i.Bucket, &i.AgentID, &i.Usage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFleetSparkDisk = `-- name: GetFleetSparkDisk :many
SELECT
    time_bucket(($1)::text::interval, d.time)::timestamptz AS bucket,
    d.agent_id,
    MAX(d.used_percent)::float8 AS max_percent
FROM metrics_disk d
WHERE d.time >= $2 AND d.time <= $3
GROUP BY 1, 2
ORDER BY 2, 1 ASC
`

type GetFleetSparkDiskParams struct {
	BucketInterval string             `json:"bucket_interval"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetFleetSparkDiskRow struct {
	Bucket     pgtype.Timestamptz `json:"bucket"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	MaxPercent float64            `json:"max_percent"`
}

func (q *Queries) GetFleetSparkDisk(ctx context.Context, arg GetFleetSparkDiskParams) ([]GetFleetSparkDiskRow, error) {
	rows, err := q.db.Query(ctx, getFleetSparkDisk, arg.BucketInterval, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFleetSparkDiskRow{}
	for rows.Next() {
		var i GetFleetSparkDiskRow
		if err := rows.Scan(&i.Bucket, &i.AgentID, &i.MaxPercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFleetSparkMemory = `-- name: GetFleetSparkMemory :many
SELECT
    time_bucket(($1)::text::interval, m.time)::timestamptz AS bucket,
    m.agent_id,
    AVG(m.ram_percent)::float8 AS ram_percent
FROM metrics_memory m
WHERE m.time >= $2 AND m.time <= $3
GROUP BY 1, 2
ORDER BY 2, 1 ASC
`

type GetFleetSparkMemoryParams struct {
	BucketInterval string             `json:"bucket_interval"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
}

type GetFleetSparkMemoryRow struct {
	Bucket     pgtype.Timestamptz `json:"bucket"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	RamPercent float64            `json:"ram_percent"`
}

func (q *Queries) GetFleetSparkMemory(ctx context.Context, arg GetFleetSparkMemoryParams) ([]GetFleetSparkMemoryRow, error) {
	rows, err := q.db.Query(ctx, getFleetSparkMemory, arg.BucketInterval, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFleetSparkMemoryRow{}
	for rows.Next() {
		var i GetFleetSparkMemoryRow
		if err := rows.Scan(&i.Bucket, &i.AgentID, &i.RamPercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentCPU = `-- name: GetRecentCPU :many
SELECT agent_id, usage
FROM (
    SELECT
        agent_id,
        usage,
        time,
        ROW_NUMBER() OVER (
            PARTITION BY agent_id
            ORDER BY time DESC
        ) AS rn
    FROM metrics_cpu
) t
WHERE rn <= 30
ORDER BY agent_id, time ASC
`

type GetRecentCPURow struct {
	AgentID pgtype.UUID   `json:"agent_id"`
	Usage   pgtype.Float8 `json:"usage"`
}

// Returns the latest 30 CPU samples per agent, ordered chronologically.
func (q *Queries) GetRecentCPU(ctx context.Context) ([]GetRecentCPURow, error) {
	rows, err := q.db.Query(ctx, getRecentCPU)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentCPURow{}
	for rows.Next() {
		var i GetRecentCPURow
		if err := rows.Scan(&i.AgentID, &i.Usage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentDiskMax = `-- name: GetRecentDiskMax :many
WITH disk_buckets AS (
    SELECT
        agent_id,
        date_trunc('minute', time) AS bucket,
        MAX(used_percent)::double precision AS max_percent
    FROM metrics_disk
    GROUP BY agent_id, date_trunc('minute', time)
),
ranked AS (
    SELECT
        agent_id,
        max_percent,
        bucket,
        ROW_NUMBER() OVER (
            PARTITION BY agent_id
            ORDER BY bucket DESC
        ) AS rn
    FROM disk_buckets
)
SELECT agent_id, max_percent
FROM ranked
WHERE rn <= 30
ORDER BY agent_id, bucket ASC
`

type GetRecentDiskMaxRow struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	MaxPercent float64     `json:"max_percent"`
}

// Returns the latest 30 disk max samples per agent, ordered chronologically.
func (q *Queries) GetRecentDiskMax(ctx context.Context) ([]GetRecentDiskMaxRow, error) {
	rows, err := q.db.Query(ctx, getRecentDiskMax)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentDiskMaxRow{}
	for rows.Next() {
		var i GetRecentDiskMaxRow
		if err := rows.Scan(&i.AgentID, &i.MaxPercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMemory = `-- name: GetRecentMemory :many
SELECT agent_id, ram_percent
FROM (
    SELECT
        agent_id,
        ram_percent,
        time,
        ROW_NUMBER() OVER (
            PARTITION BY agent_id
            ORDER BY time DESC
        ) AS rn
    FROM metrics_memory
) t
WHERE rn <= 30
ORDER BY agent_id, time ASC
`

type GetRecentMemoryRow struct {
	AgentID    pgtype.UUID   `json:"agent_id"`
	RamPercent pgtype.Float8 `json:"ram_percent"`
}

// Returns the latest 30 RAM samples per agent, ordered chronologically.
func (q *Queries) GetRecentMemory(ctx context.Context) ([]GetRecentMemoryRow, error) {
	rows, err := q.db.Query(ctx, getRecentMemory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentMemoryRow{}
	for rows.Next() {
		var i GetRecentMemoryRow
		if err := rows.Scan(&i.AgentID, &i.RamPercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
