// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: status_thresholds.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStatusThresholds = `-- name: GetStatusThresholds :one
SELECT cpu_warn, cpu_crit, mem_warn, mem_crit, disk_warn, disk_crit,
	   temp_warn, temp_crit, stale_seconds, offline_seconds, updated_at
FROM status_thresholds
WHERE id = 1
`

type GetStatusThresholdsRow struct {
	CpuWarn        float64            `json:"cpu_warn"`
	CpuCrit        float64            `json:"cpu_crit"`
	MemWarn        float64            `json:"mem_warn"`
	MemCrit        float64            `json:"mem_crit"`
	DiskWarn       float64            `json:"disk_warn"`
	DiskCrit       float64            `json:"disk_crit"`
	TempWarn       float64            `json:"temp_warn"`
	TempCrit       float64            `json:"temp_crit"`
	StaleSeconds   int32              `json:"stale_seconds"`
	OfflineSeconds int32              `json:"offline_seconds"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Load the global state thresholds. The table holds a single row (id = 1,
// enforced by a CHECK), seeded with defaults by the migration, so this read
// always returns exactly one row.
func (q *Queries) GetStatusThresholds(ctx context.Context) (GetStatusThresholdsRow, error) {
	row := q.db.QueryRow(ctx, getStatusThresholds)
	var i GetStatusThresholdsRow
	err := row.Scan(
		&i.CpuWarn,
		&i.CpuCrit,
		&i.MemWarn,
		&i.MemCrit,
		&i.DiskWarn,
		&i.DiskCrit,
		&i.TempWarn,
		&i.TempCrit,
		&i.StaleSeconds,
		&i.OfflineSeconds,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStatusThresholds = `-- name: UpsertStatusThresholds :exec
INSERT INTO status_thresholds (
	id, cpu_warn, cpu_crit, mem_warn, mem_crit, disk_warn, disk_crit,
	temp_warn, temp_crit, stale_seconds, offline_seconds, updated_at
) VALUES (
	1, $1, $2, $3, $4, $5, $6,
	$7, $8, $9, $10, NOW()
)
ON CONFLICT (id) DO UPDATE
SET cpu_warn = EXCLUDED.cpu_warn,
    cpu_crit = EXCLUDED.cpu_crit,
    mem_warn = EXCLUDED.mem_warn,
    mem_crit = EXCLUDED.mem_crit,
    disk_warn = EXCLUDED.disk_warn,
    disk_crit = EXCLUDED.disk_crit,
    temp_warn = EXCLUDED.temp_warn,
    temp_crit = EXCLUDED.temp_crit,
    stale_seconds = EXCLUDED.stale_seconds,
    offline_seconds = EXCLUDED.offline_seconds,
    updated_at = NOW()
`

type UpsertStatusThresholdsParams struct {
	CpuWarn        float64 `json:"cpu_warn"`
	CpuCrit        float64 `json:"cpu_crit"`
	MemWarn        float64 `json:"mem_warn"`
	MemCrit        float64 `json:"mem_crit"`
	DiskWarn       float64 `json:"disk_warn"`
	DiskCrit       float64 `json:"disk_crit"`
	TempWarn       float64 `json:"temp_warn"`
	TempCrit       float64 `json:"temp_crit"`
	StaleSeconds   int32   `json:"stale_seconds"`
	OfflineSeconds int32   `json:"offline_seconds"`
}

// Replace the global status thresholds. Targets the singleton row (id = 1);
// the ON CONFLICT branch updates in place when the row already exists, which it
// always does after the migration seed.
func (q *Queries) UpsertStatusThresholds(ctx context.Context, arg UpsertStatusThresholdsParams) error {
	_, err := q.db.Exec(ctx, upsertStatusThresholds,
		arg.CpuWarn,
		arg.CpuCrit,
		arg.MemWarn,
		arg.MemCrit,
		arg.DiskWarn,
		arg.DiskCrit,
		arg.TempWarn,
		arg.TempCrit,
		arg.StaleSeconds,
		arg.OfflineSeconds,
	)
	return err
}
