// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredTokens = `-- name: CleanExpiredTokens :exec
DELETE FROM registration_tokens WHERE expires_at < NOW() AND used
`

func (q *Queries) CleanExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredTokens)
	return err
}

const createToken = `-- name: CreateToken :exec
INSERT INTO registration_tokens (token, expires_at)
VALUES ($1, $2)
`

type CreateTokenParams struct {
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken, arg.Token, arg.ExpiresAt)
	return err
}

const validateAndUseToken = `-- name: ValidateAndUseToken :one
UPDATE registration_tokens
SET used = TRUE, used_by = $2
WHERE token = $1 AND NOT used AND expires_at > NOW()
RETURNING token
`

type ValidateAndUseTokenParams struct {
	Token  string      `json:"token"`
	UsedBy pgtype.UUID `json:"used_by"`
}

func (q *Queries) ValidateAndUseToken(ctx context.Context, arg ValidateAndUseTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, validateAndUseToken, arg.Token, arg.UsedBy)
	var token string
	err := row.Scan(&token)
	return token, err
}
