// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserConfig = `-- name: DeleteUserConfig :exec
DELETE FROM user_config
WHERE user_id = $1 AND config_key = $2
`

type DeleteUserConfigParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ConfigKey string      `json:"config_key"`
}

func (q *Queries) DeleteUserConfig(ctx context.Context, arg DeleteUserConfigParams) error {
	_, err := q.db.Exec(ctx, deleteUserConfig, arg.UserID, arg.ConfigKey)
	return err
}

const getUserConfig = `-- name: GetUserConfig :many
SELECT config_key, config_value
FROM user_config
WHERE user_id = $1
`

type GetUserConfigRow struct {
	ConfigKey   string `json:"config_key"`
	ConfigValue []byte `json:"config_value"`
}

func (q *Queries) GetUserConfig(ctx context.Context, userID pgtype.UUID) ([]GetUserConfigRow, error) {
	rows, err := q.db.Query(ctx, getUserConfig, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserConfigRow{}
	for rows.Next() {
		var i GetUserConfigRow
		if err := rows.Scan(&i.ConfigKey, &i.ConfigValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserConfigKey = `-- name: GetUserConfigKey :one
SELECT config_value
FROM user_config
WHERE user_id = $1 AND config_key = $2
`

type GetUserConfigKeyParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ConfigKey string      `json:"config_key"`
}

func (q *Queries) GetUserConfigKey(ctx context.Context, arg GetUserConfigKeyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserConfigKey, arg.UserID, arg.ConfigKey)
	var config_value []byte
	err := row.Scan(&config_value)
	return config_value, err
}

const setUserConfig = `-- name: SetUserConfig :exec
INSERT INTO user_config (user_id, config_key, config_value, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, config_key)
DO UPDATE SET config_value = EXCLUDED.config_value, updated_at = NOW()
`

type SetUserConfigParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ConfigKey   string      `json:"config_key"`
	ConfigValue []byte      `json:"config_value"`
}

func (q *Queries) SetUserConfig(ctx context.Context, arg SetUserConfigParams) error {
	_, err := q.db.Exec(ctx, setUserConfig, arg.UserID, arg.ConfigKey, arg.ConfigValue)
	return err
}
