version: "2"
linters:
  enable:
    - containedctx
    - errchkjson
    - errorlint
    - forcetypeassert
    - goconst
    - gosec
    - revive
  disable:
    - cyclop
    - depguard
    - dogsled
    - err113
    - errname
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
  settings:
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - containedctx
          - errcheck
          - errchkjson
          - forcetypeassert
          - goconst
        path: _test\.go
      - linters:
          - gosec
        path: _test\.go
        text: G404|G306
      - linters:
          - revive
        text: var-declaration|unused-parameter|empty-block|redefines-builtin-id
      - linters:
          - goconst
        text: linux|other|ping
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
