ALTER TABLE metrics_disk_io
	ADD COLUMN IF NOT EXISTS read_latency_ms	DOUBLE PRECISION,
	ADD COLUMN IF NOT EXISTS write_latency_ms	DOUBLE PRECISION,
	ADD COLUMN IF NOT EXISTS read_busy_pct		DOUBLE PRECISION,
	ADD COLUMN IF NOT EXISTS write_busy_pct		DOUBLE PRECISION;